using Luotsi.Cli.Models;

namespace Luotsi.Cli.Cli.Replay;

internal static class ReplayGraphTaxonomy
{
    public static ReplayGraphTaxonomyResult Build(string artifactRoot) => new(
        NodeKinds:
        [
            new("session", "One session-replay.json session."),
            new("event", "One normalized session-timeline.jsonl event."),
            new("failure", "Failure-relevant timeline event or terminal failure."),
            new("failure_capsule", "failure-capsule.json summary node."),
            new("scenario", "Scenario entry from a failure capsule."),
            new("artifact", "Screenshot, logcat, hierarchy, report, or metadata file linked to a scenario."),
            new("action", "Promoted action or command such as waitVisible, tap_text, or take_screenshot."),
            new("selector", "Promoted selector, currently text-based."),
            new("screen_state", "Screen or screenshot observation."),
            new("telemetry_signal", "Semantic telemetry signal emitted by the app or observed by Luotsi."),
            new("scenario_draft", "Generated scenario draft summary."),
            new("generated_step", "Step generated by replay scenario-draft."),
            new("draft_source", "Source family for generated steps, such as inspect command or telemetry."),
            new("draft_normalization", "Cleanup or normalization applied while generating a draft.")
        ],
        EdgeKinds:
        [
            new("next", "Timeline ordering within one source timeline file."),
            new("transitions_to", "Semantic timeline transition with from/to types, category, details, and optional elapsed_ms."),
            new("indicates", "Event points to a failure node."),
            new("has_capsule", "Session has a failure capsule."),
            new("contains", "Capsule contains a scenario."),
            new("has_artifact", "Scenario links to an artifact."),
            new("describes_action", "Event describes an action node."),
            new("mentions_selector", "Event mentions a selector node."),
            new("observes_screen", "Event observes a screen or screenshot state."),
            new("observes_telemetry", "Event observes a semantic telemetry signal."),
            new("generates_step", "Scenario draft generates a step."),
            new("derived_from", "Generated step came from a source event family."),
            new("uses_source", "Scenario draft uses a source family."),
            new("applies_normalization", "Scenario draft applied a normalization.")
        ],
        QueryExamples:
        [
            new("failures", "Return failure-relevant graph context.", $"luotsi replay graph --artifacts {Quote(artifactRoot)} --failed --write-markdown"),
            new("selectors", "List promoted selectors and local context.", $"luotsi replay graph --artifacts {Quote(artifactRoot)} --node-kind selector --write-markdown"),
            new("transitions", "List semantic timeline transitions.", $"luotsi replay graph --artifacts {Quote(artifactRoot)} --edge-kind transitions_to --limit 50"),
            new("neighborhood", "Expand around a specific node id returned by a previous graph query.", $"luotsi replay graph --artifacts {Quote(artifactRoot)} --node <node-id> --depth 2")
        ]);

    private static string Quote(string value) => value.Contains(' ', StringComparison.Ordinal) ? $"\"{value}\"" : value;
}
