using System.Text;
using System.Text.Json;
using Luotsi.Cli.Artifacts;
using Luotsi.Cli.Errors;
using Luotsi.Cli.Infrastructure.Contracts;
using Luotsi.Cli.Infrastructure.Serialization;
using Luotsi.Cli.Models;

namespace Luotsi.Cli.Cli.Replay;

internal sealed class ReplayScenarioDraftService(IFileSystem fileSystem)
{
    private const string ScenarioDraftSummaryFileName = "scenario-draft-summary.json";
    private const string ScenarioDraftReviewFileName = "scenario-draft.md";
    private readonly IFileSystem _fileSystem = fileSystem ?? throw new ArgumentNullException(nameof(fileSystem));

    public async Task<ReplayScenarioDraftResult> CreateAsync(CliOptions options, ArtifactSession artifacts)
    {
        ArgumentNullException.ThrowIfNull(options);
        ArgumentNullException.ThrowIfNull(artifacts);

        var output = options.Get("output") ?? options.Get("file");
        var events = ReadTimelineEvents(artifacts.Root);
        var steps = CreateSteps(events);
        if (steps.Count == 0)
        {
            throw new UsageException("replay scenario-draft could not find action events in session-timeline.jsonl.");
        }

        var warnings = BuildWarnings(steps).ToArray();
        var jsonPath = options.HasFlag("write-json")
            ? Path.Join(artifacts.Root, ScenarioDraftSummaryFileName)
            : null;
        var markdownPath = options.HasFlag("write-markdown")
            ? Path.Join(artifacts.Root, ScenarioDraftReviewFileName)
            : null;
        var scenario = new ScenarioFile(
            options.Get("name") ?? "draft from replay",
            steps,
            Tags: ["draft", "generated", "replay"],
            Metadata: new ScenarioMetadata(
                Notes: $"Generated by `luotsi replay scenario-draft` from artifact root {artifacts.Root}. Review selectors, waits, and coordinate-specific steps before committing."));
        var suggestions = BuildSuggestions(steps).ToArray();
        var result = new ReplayScenarioDraftResult(
            ResultSchemas.ScenarioDraft,
            artifacts.Root,
            output,
            jsonPath,
            markdownPath,
            warnings.Length == 0 ? "medium" : "low",
            warnings,
            scenario,
            suggestions);

        if (!string.IsNullOrWhiteSpace(output))
        {
            var directory = Path.GetDirectoryName(output);
            if (!string.IsNullOrWhiteSpace(directory))
            {
                _fileSystem.CreateDirectory(directory);
            }

            await _fileSystem.WriteAllTextAsync(output, JsonSerializer.Serialize(scenario, AppJson.Options) + Environment.NewLine, new UTF8Encoding(false)).ConfigureAwait(false);
        }

        if (jsonPath is not null)
        {
            await artifacts.WriteJsonAsync(ScenarioDraftSummaryFileName, result).ConfigureAwait(false);
        }

        if (markdownPath is not null)
        {
            await artifacts.WriteTextAsync(ScenarioDraftReviewFileName, BuildMarkdown(result)).ConfigureAwait(false);
        }

        return result;
    }

    private static string BuildMarkdown(ReplayScenarioDraftResult result)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Luotsi Scenario Draft");
        builder.AppendLine();
        builder.AppendLine($"Artifact root: `{result.ArtifactRoot}`");
        builder.AppendLine($"Scenario: `{result.Scenario.Name}`");
        builder.AppendLine($"Output: `{result.Output ?? "(not written)"}`");
        builder.AppendLine($"Confidence: `{result.Confidence}`");
        builder.AppendLine($"Steps: `{result.Scenario.Steps.Count}`");
        builder.AppendLine();
        builder.AppendLine("## Warnings");
        builder.AppendLine();
        if (result.Warnings.Count == 0)
        {
            builder.AppendLine("- None");
        }
        else
        {
            foreach (var warning in result.Warnings)
            {
                builder.AppendLine("- " + warning);
            }
        }

        builder.AppendLine();
        builder.AppendLine("## Suggestions");
        builder.AppendLine();
        if (result.Suggestions.Count == 0)
        {
            builder.AppendLine("- None");
        }
        else
        {
            foreach (var suggestion in result.Suggestions)
            {
                builder.AppendLine($"- Step {suggestion.StepIndex}: `{suggestion.Kind}` ({suggestion.Confidence}) - {suggestion.Message}");
            }
        }

        builder.AppendLine();
        builder.AppendLine("## Draft Steps");
        builder.AppendLine();
        builder.AppendLine("| # | Action | Name | Text/Code/Label |");
        builder.AppendLine("|---:|---|---|---|");
        for (var i = 0; i < result.Scenario.Steps.Count; i++)
        {
            var step = result.Scenario.Steps[i];
            builder.Append("| ");
            builder.Append(i + 1);
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(step.Action));
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(step.Name ?? string.Empty));
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(step.Text ?? step.Code ?? step.Label ?? string.Empty));
            builder.AppendLine(" |");
        }

        return builder.ToString();
    }

    private static string EscapeMarkdown(string value) =>
        value.Replace("|", "\\|", StringComparison.Ordinal)
            .Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal);

    private IReadOnlyList<JsonElement> ReadTimelineEvents(string artifactRoot)
    {
        var files = _fileSystem.GetFiles(artifactRoot, SessionReplayArtifacts.TimelineFileName, SearchOption.AllDirectories);
        if (files.Count == 0)
        {
            throw new UsageException($"No {SessionReplayArtifacts.TimelineFileName} was found under artifact root '{artifactRoot}'.");
        }

        return files.Order(StringComparer.OrdinalIgnoreCase)
            .SelectMany(ReadTimelineEventsFromFile)
            .ToArray();
    }

    private IEnumerable<JsonElement> ReadTimelineEventsFromFile(string file)
    {
        using var stream = _fileSystem.OpenRead(file);
        using var reader = new StreamReader(stream, Encoding.UTF8, detectEncodingFromByteOrderMarks: true, bufferSize: 4096);
        while (reader.ReadLine() is { } line)
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }

            var evt = ParseTimelineEvent(file, line);
            if (evt is not null)
            {
                yield return evt.Value;
            }
        }
    }

    private static JsonElement? ParseTimelineEvent(string file, string line)
    {
        try
        {
            using var document = JsonDocument.Parse(line);
            return document.RootElement.ValueKind == JsonValueKind.Object
                ? document.RootElement.Clone()
                : null;
        }
        catch (JsonException ex)
        {
            throw new UsageException($"replay scenario-draft encountered invalid JSON in '{file}'. {ex.Message} Line: {line}");
        }
    }

    private static IReadOnlyList<ScenarioStep> CreateSteps(IReadOnlyList<JsonElement> events)
    {
        var steps = new List<ScenarioStep>();
        foreach (var evt in events)
        {
            if (!TryGetString(evt, "type", out var type))
            {
                continue;
            }

            var step = type switch
            {
                "command_result" => CreateInspectCommandStep(evt),
                "scenario_step_passed" or "scenario_step_continued_on_error" or "scenario_step_failed" => CreateScenarioStep(evt),
                "view_screenshot_captured" => CreateScreenshotStep(evt),
                "view_key_command_sent" => CreateKeyCommandStep(evt),
                _ => null
            };

            if (step is not null)
            {
                steps.Add(step);
            }
        }

        return steps;
    }

    private static ScenarioStep? CreateInspectCommandStep(JsonElement evt)
    {
        if (!TryGetString(evt, "command", out var command) || TryGetBool(evt, "ok") is false)
        {
            return null;
        }

        var data = evt.TryGetProperty("data", out var dataElement) && dataElement.ValueKind == JsonValueKind.Object
            ? dataElement
            : default;
        return command switch
        {
            "tap_text" => CreateTextStep(data, "tapText", "tap text"),
            "wait_visible" => CreateTextStep(data, "waitVisible", "wait visible"),
            "type_text" => CreateTextStep(data, "typeText", "type text"),
            "keyevent" => TryGetString(data, "code", out var code)
                ? new ScenarioStep("keyevent " + code, "keyevent", null, code, null)
                : null,
            "screenshot" or "take_screenshot" => CreateLabelStep(data, "takeScreenshot", "screenshot"),
            _ => null
        };
    }

    private static ScenarioStep? CreateScenarioStep(JsonElement evt)
    {
        if (!TryGetString(evt, "action", out var action))
        {
            return null;
        }

        TryGetString(evt, "step", out var name);
        var stepName = name ?? action;
        return action switch
        {
            "waitVisible" or "waitNotVisible" or "tapText" or "typeText" or "waitLog" => TryGetString(evt, "text", out var text)
                ? new ScenarioStep(stepName, action, text, null, null, TimeoutSec: action.StartsWith("wait", StringComparison.OrdinalIgnoreCase) ? 15 : null)
                : null,
            "keyevent" => TryGetString(evt, "code", out var code)
                ? new ScenarioStep(stepName, action, null, code, null)
                : null,
            "waitStep" => TryGetString(evt, "step", out var waitStep)
                ? new ScenarioStep(stepName, action, null, null, waitStep, TimeoutSec: 15)
                : null,
            "takeScreenshot" => new ScenarioStep(stepName, action, null, null, null, Label: stepName),
            "captureArtifacts" => new ScenarioStep(stepName, action, null, null, null, Label: stepName),
            _ => null
        };
    }

    private static ScenarioStep? CreateScreenshotStep(JsonElement evt)
    {
        var label = TryGetOptionalString(evt, "label") ?? "replay-screenshot";
        return new ScenarioStep("capture " + label, "takeScreenshot", null, null, null, Label: label);
    }

    private static ScenarioStep? CreateKeyCommandStep(JsonElement evt)
    {
        if (!TryGetString(evt, "command", out var command))
        {
            return null;
        }

        return new ScenarioStep("key command " + command, "keyevent", null, command, null);
    }

    private static ScenarioStep? CreateTextStep(JsonElement data, string action, string fallbackName)
    {
        if (!TryGetString(data, "text", out var text))
        {
            return null;
        }

        return new ScenarioStep(fallbackName + " " + text, action, text, null, null, TimeoutSec: action.StartsWith("wait", StringComparison.OrdinalIgnoreCase) ? 15 : null);
    }

    private static ScenarioStep? CreateLabelStep(JsonElement data, string action, string fallbackLabel)
    {
        var label = TryGetOptionalString(data, "label") ?? fallbackLabel;
        return new ScenarioStep("capture " + label, action, null, null, null, Label: label);
    }

    private static IEnumerable<string> BuildWarnings(IReadOnlyList<ScenarioStep> steps)
    {
        if (steps.Any(static step => string.Equals(step.Action, "tapPoint", StringComparison.OrdinalIgnoreCase)))
        {
            yield return "Draft includes coordinate taps; add scenario metadata for device layout before using in CI.";
        }

        if (steps.All(static step => !string.Equals(step.Action, "waitVisible", StringComparison.OrdinalIgnoreCase)))
        {
            yield return "Draft has no waitVisible steps; add waits around asynchronous UI transitions.";
        }
    }

    private static IEnumerable<ReplayScenarioDraftSuggestion> BuildSuggestions(IReadOnlyList<ScenarioStep> steps)
    {
        for (var i = 0; i < steps.Count; i++)
        {
            var step = steps[i];
            if (string.Equals(step.Action, "tapText", StringComparison.OrdinalIgnoreCase))
            {
                yield return new ReplayScenarioDraftSuggestion(i + 1, "selector", "medium", "Review whether this tap should be preceded by waitVisible for the same text.");
            }
            else if (string.Equals(step.Action, "tapPoint", StringComparison.OrdinalIgnoreCase))
            {
                yield return new ReplayScenarioDraftSuggestion(i + 1, "coordinate", "low", "Replace coordinate tap with tapText or add layout metadata if possible.");
            }
            else if (string.Equals(step.Action, "takeScreenshot", StringComparison.OrdinalIgnoreCase))
            {
                yield return new ReplayScenarioDraftSuggestion(i + 1, "visual", "medium", "Consider upgrading screenshot capture to assertScreenshot with a baseline or region hash.");
            }
        }
    }

    private static bool TryGetString(JsonElement root, string name, out string value)
    {
        value = string.Empty;
        if (root.ValueKind != JsonValueKind.Object ||
            !root.TryGetProperty(name, out var property) ||
            property.ValueKind != JsonValueKind.String ||
            string.IsNullOrWhiteSpace(property.GetString()))
        {
            return false;
        }

        value = property.GetString()!;
        return true;
    }

    private static string? TryGetOptionalString(JsonElement root, string name) =>
        TryGetString(root, name, out var value) ? value : null;

    private static bool? TryGetBool(JsonElement root, string name)
    {
        if (root.ValueKind != JsonValueKind.Object ||
            !root.TryGetProperty(name, out var property) ||
            property.ValueKind is not JsonValueKind.True and not JsonValueKind.False)
        {
            return null;
        }

        return property.GetBoolean();
    }
}
