using System.Linq;
using System.Text;
using System.Text.Json;
using Luotsi.Cli.Artifacts;
using Luotsi.Cli.Errors;
using Luotsi.Cli.Infrastructure.Contracts;
using Luotsi.Cli.Infrastructure.Serialization;
using Luotsi.Cli.Models;

namespace Luotsi.Cli.Cli.Replay;

internal sealed class ReplayScenarioDraftService(IFileSystem fileSystem)
{
    private const string ScenarioDraftSummaryFileName = "scenario-draft-summary.json";
    private const string ScenarioDraftReviewFileName = "scenario-draft.md";
    private readonly IFileSystem _fileSystem = fileSystem ?? throw new ArgumentNullException(nameof(fileSystem));

    public async Task<ReplayScenarioDraftResult> CreateAsync(CliOptions options, ArtifactSession artifacts)
    {
        ArgumentNullException.ThrowIfNull(options);
        ArgumentNullException.ThrowIfNull(artifacts);

        var output = options.Get("output") ?? options.Get("file");
        var events = ReadTimelineEvents(artifacts.Root);
        var normalizationNotes = new List<ReplayScenarioDraftNormalization>();
        var draftSteps = NormalizeSteps(CreateSteps(events), normalizationNotes);
        if (draftSteps.Count == 0)
        {
            throw new UsageException("replay scenario-draft could not find action events in session-timeline.jsonl.");
        }

        var steps = draftSteps.Select(static step => step.Step).ToArray();
        var warnings = BuildWarnings(steps).ToArray();
        var jsonPath = options.HasFlag("write-json")
            ? Path.Join(artifacts.Root, ScenarioDraftSummaryFileName)
            : null;
        var markdownPath = options.HasFlag("write-markdown")
            ? Path.Join(artifacts.Root, ScenarioDraftReviewFileName)
            : null;
        var scenario = new ScenarioFile(
            options.Get("name") ?? "draft from replay",
            steps,
            Tags: ["draft", "generated", "replay"],
            Metadata: new ScenarioMetadata(
                Notes: $"Generated by `luotsi replay scenario-draft` from artifact root {artifacts.Root}. Review selectors, waits, and coordinate-specific steps before committing."));
        var suggestions = BuildSuggestions(steps).ToArray();
        var origins = draftSteps
            .Select((step, index) => new ReplayScenarioDraftStepOrigin(
                index + 1,
                step.Source,
                step.EventType,
                step.Command,
                step.Detail,
                step.Confidence))
            .ToArray();
        var sourceSummaries = BuildSourceSummaries(origins, normalizationNotes).ToArray();
        var result = new ReplayScenarioDraftResult(
            ResultSchemas.ScenarioDraft,
            artifacts.Root,
            output,
            jsonPath,
            markdownPath,
            warnings.Length == 0 ? "medium" : "low",
            warnings,
            scenario,
            suggestions,
            sourceSummaries,
            origins,
            normalizationNotes);

        if (!string.IsNullOrWhiteSpace(output))
        {
            var directory = Path.GetDirectoryName(output);
            if (!string.IsNullOrWhiteSpace(directory))
            {
                _fileSystem.CreateDirectory(directory);
            }

            await _fileSystem.WriteAllTextAsync(output, JsonSerializer.Serialize(scenario, AppJson.Options) + Environment.NewLine, new UTF8Encoding(false)).ConfigureAwait(false);
        }

        if (jsonPath is not null)
        {
            await artifacts.WriteJsonAsync(ScenarioDraftSummaryFileName, result).ConfigureAwait(false);
        }

        if (markdownPath is not null)
        {
            await artifacts.WriteTextAsync(ScenarioDraftReviewFileName, BuildMarkdown(result)).ConfigureAwait(false);
        }

        return result;
    }

    private static IReadOnlyList<DraftStep> NormalizeSteps(
        IReadOnlyList<DraftStep> steps,
        ICollection<ReplayScenarioDraftNormalization> normalizations)
    {
        var normalized = new List<DraftStep>();
        foreach (var step in steps)
        {
            if (TryCreateDuplicateWaitNormalization(normalized, step, out var normalization))
            {
                normalizations.Add(normalization);
                continue;
            }

            normalized.Add(step);
        }

        return normalized;
    }

    private static bool TryCreateDuplicateWaitNormalization(
        IReadOnlyList<DraftStep> normalized,
        DraftStep candidate,
        out ReplayScenarioDraftNormalization normalization)
    {
        normalization = default!;
        var candidateKey = GetWaitKey(candidate.Step);
        if (candidateKey is null)
        {
            return false;
        }

        var previous = normalized.LastOrDefault();
        if (previous is null || !string.Equals(GetWaitKey(previous.Step), candidateKey, StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        normalization = new ReplayScenarioDraftNormalization(
            "duplicate_wait",
            $"Dropped adjacent duplicate {candidate.Step.Action} for `{GetStepTarget(candidate.Step)}`.",
            candidate.Source,
            candidate.EventType,
            candidate.Confidence);
        return true;
    }

    private static string? GetWaitKey(ScenarioStep step) =>
        step.Action switch
        {
            "waitVisible" when !string.IsNullOrWhiteSpace(step.Text) => "waitVisible:" + step.Text,
            "waitStep" when !string.IsNullOrWhiteSpace(step.Step) => "waitStep:" + step.Step,
            "waitActionReady" when !string.IsNullOrWhiteSpace(step.Text) => "waitActionReady:" + step.Step + ":" + step.Text,
            "assertEvent" when !string.IsNullOrWhiteSpace(step.Event) => "assertEvent:" + step.Event,
            _ => null
        };

    private static string GetStepTarget(ScenarioStep step) =>
        step.Text ?? step.Step ?? step.Event ?? step.Code ?? step.Label ?? step.Action;

    private static IEnumerable<ReplayScenarioDraftSourceSummary> BuildSourceSummaries(
        IReadOnlyList<ReplayScenarioDraftStepOrigin> origins,
        IReadOnlyList<ReplayScenarioDraftNormalization> normalizations)
    {
        var sources = origins
            .Select(static origin => origin.Source)
            .Concat(normalizations.Select(static normalization => normalization.Source))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(static source => source, StringComparer.OrdinalIgnoreCase);

        foreach (var source in sources)
        {
            var sourceOrigins = origins
                .Where(origin => string.Equals(origin.Source, source, StringComparison.OrdinalIgnoreCase))
                .ToArray();
            var sourceNormalizations = normalizations.Count(normalization =>
                string.Equals(normalization.Source, source, StringComparison.OrdinalIgnoreCase));
            var eventTypes = sourceOrigins
                .Select(static origin => origin.EventType)
                .Concat(normalizations
                    .Where(normalization => string.Equals(normalization.Source, source, StringComparison.OrdinalIgnoreCase))
                    .Select(static normalization => normalization.EventType))
                .Where(static eventType => !string.IsNullOrWhiteSpace(eventType))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderBy(static eventType => eventType, StringComparer.OrdinalIgnoreCase)
                .ToArray();

            yield return new ReplayScenarioDraftSourceSummary(
                source,
                sourceOrigins.Length,
                sourceNormalizations,
                eventTypes,
                SummarizeConfidence(sourceOrigins.Select(static origin => origin.Confidence)
                    .Concat(normalizations
                        .Where(normalization => string.Equals(normalization.Source, source, StringComparison.OrdinalIgnoreCase))
                        .Select(static normalization => normalization.Confidence))));
        }
    }

    private static string SummarizeConfidence(IEnumerable<string> confidenceValues)
    {
        var values = confidenceValues.ToArray();
        if (values.Any(static value => string.Equals(value, "low", StringComparison.OrdinalIgnoreCase)))
        {
            return "low";
        }

        if (values.Any(static value => string.Equals(value, "medium", StringComparison.OrdinalIgnoreCase)))
        {
            return "medium";
        }

        return values.Length == 0 ? "unknown" : "high";
    }

    private static string BuildMarkdown(ReplayScenarioDraftResult result)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Luotsi Scenario Draft");
        builder.AppendLine();
        builder.AppendLine($"Artifact root: `{result.ArtifactRoot}`");
        builder.AppendLine($"Scenario: `{result.Scenario.Name}`");
        builder.AppendLine($"Output: `{result.Output ?? "(not written)"}`");
        builder.AppendLine($"Confidence: `{result.Confidence}`");
        builder.AppendLine($"Steps: `{result.Scenario.Steps.Count}`");
        builder.AppendLine();
        builder.AppendLine("## Warnings");
        builder.AppendLine();
        if (result.Warnings.Count == 0)
        {
            builder.AppendLine("- None");
        }
        else
        {
            foreach (var warning in result.Warnings)
            {
                builder.AppendLine("- " + warning);
            }
        }

        builder.AppendLine();
        builder.AppendLine("## Suggestions");
        builder.AppendLine();
        if (result.Suggestions.Count == 0)
        {
            builder.AppendLine("- None");
        }
        else
        {
            foreach (var suggestion in result.Suggestions)
            {
                builder.AppendLine($"- Step {suggestion.StepIndex}: `{suggestion.Kind}` ({suggestion.Confidence}) - {suggestion.Message}");
            }
        }

        builder.AppendLine();
        builder.AppendLine("## Source Summary");
        builder.AppendLine();
        builder.AppendLine("| Source | Steps | Normalizations | Events | Confidence |");
        builder.AppendLine("|---|---:|---:|---|---|");
        foreach (var summary in result.SourceSummaries)
        {
            builder.Append("| ");
            builder.Append(EscapeMarkdown(summary.Source));
            builder.Append(" | ");
            builder.Append(summary.StepCount);
            builder.Append(" | ");
            builder.Append(summary.NormalizationCount);
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(string.Join(", ", summary.EventTypes)));
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(summary.Confidence));
            builder.AppendLine(" |");
        }

        builder.AppendLine();
        builder.AppendLine("## Normalizations");
        builder.AppendLine();
        if (result.Normalizations.Count == 0)
        {
            builder.AppendLine("- None");
        }
        else
        {
            foreach (var normalization in result.Normalizations)
            {
                builder.AppendLine($"- `{normalization.Kind}` ({normalization.Confidence}) from `{normalization.Source}`: {normalization.Detail}");
            }
        }

        builder.AppendLine();
        builder.AppendLine("## Step Origins");
        builder.AppendLine();
        builder.AppendLine("| # | Source | Event | Command | Confidence | Detail |");
        builder.AppendLine("|---:|---|---|---|---|---|");
        foreach (var origin in result.StepOrigins)
        {
            builder.Append("| ");
            builder.Append(origin.StepIndex);
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(origin.Source));
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(origin.EventType));
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(origin.Command ?? string.Empty));
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(origin.Confidence));
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(origin.Detail ?? string.Empty));
            builder.AppendLine(" |");
        }

        builder.AppendLine();
        builder.AppendLine("## Draft Steps");
        builder.AppendLine();
        builder.AppendLine("| # | Action | Name | Text/Code/Label |");
        builder.AppendLine("|---:|---|---|---|");
        for (var i = 0; i < result.Scenario.Steps.Count; i++)
        {
            var step = result.Scenario.Steps[i];
            builder.Append("| ");
            builder.Append(i + 1);
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(step.Action));
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(step.Name ?? string.Empty));
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(step.Text ?? step.Code ?? step.Label ?? string.Empty));
            builder.AppendLine(" |");
        }

        return builder.ToString();
    }

    private static string EscapeMarkdown(string value) =>
        value.Replace("|", "\\|", StringComparison.Ordinal)
            .Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal);

    private IReadOnlyList<JsonElement> ReadTimelineEvents(string artifactRoot)
    {
        var files = _fileSystem.GetFiles(artifactRoot, SessionReplayArtifacts.TimelineFileName, SearchOption.AllDirectories);
        if (files.Count == 0)
        {
            throw new UsageException($"No {SessionReplayArtifacts.TimelineFileName} was found under artifact root '{artifactRoot}'.");
        }

        return files.Order(StringComparer.OrdinalIgnoreCase)
            .SelectMany(ReadTimelineEventsFromFile)
            .ToArray();
    }

    private IEnumerable<JsonElement> ReadTimelineEventsFromFile(string file)
    {
        using var stream = _fileSystem.OpenRead(file);
        using var reader = new StreamReader(stream, Encoding.UTF8, detectEncodingFromByteOrderMarks: true, bufferSize: 4096);
        while (reader.ReadLine() is { } line)
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }

            var evt = ParseTimelineEvent(file, line);
            if (evt is not null)
            {
                yield return evt.Value;
            }
        }
    }

    private static JsonElement? ParseTimelineEvent(string file, string line)
    {
        try
        {
            using var document = JsonDocument.Parse(line);
            return document.RootElement.ValueKind == JsonValueKind.Object
                ? document.RootElement.Clone()
                : null;
        }
        catch (JsonException ex)
        {
            throw new UsageException($"replay scenario-draft encountered invalid JSON in '{file}'. {ex.Message} Line: {line}");
        }
    }

    private static IReadOnlyList<DraftStep> CreateSteps(IReadOnlyList<JsonElement> events)
    {
        var steps = new List<DraftStep>();
        foreach (var evt in events)
        {
            if (!TryGetString(evt, "type", out var type))
            {
                continue;
            }

            if (string.Equals(type, "command_result", StringComparison.Ordinal))
            {
                steps.AddRange(CreateInspectCommandSteps(evt));
                continue;
            }

            if (string.Equals(type, "screen_delta", StringComparison.Ordinal))
            {
                steps.AddRange(CreateScreenDeltaSteps(evt));
                continue;
            }

            var step = type switch
            {
                "scenario_step_passed" or "scenario_step_continued_on_error" or "scenario_step_failed" => CreateScenarioStep(evt, type),
                "view_screenshot_captured" => CreateScreenshotStep(evt, type),
                "view_key_command_sent" => CreateKeyCommandStep(evt, type),
                _ => null
            };

            if (step is not null)
            {
                steps.Add(step);
            }
        }

        return steps;
    }

    private static IReadOnlyList<DraftStep> CreateScreenDeltaSteps(JsonElement evt)
    {
        if (!evt.TryGetProperty("delta", out var delta) ||
            delta.ValueKind != JsonValueKind.Object ||
            !delta.TryGetProperty("added", out var added) ||
            added.ValueKind != JsonValueKind.Array)
        {
            return [];
        }

        var steps = new List<DraftStep>();
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var element in added.EnumerateArray())
        {
            var text = TryGetOptionalString(element, "text") ?? TryGetOptionalString(element, "content_description");
            if (string.IsNullOrWhiteSpace(text) || !seen.Add(text))
            {
                continue;
            }

            steps.Add(new DraftStep(
                new ScenarioStep("wait visible " + text, "waitVisible", text, null, null, TimeoutSec: 15),
                "screen_delta",
                "screen_delta",
                null,
                "added text: " + text,
                "medium"));
            if (steps.Count == 3)
            {
                break;
            }
        }

        return steps;
    }

    private static IReadOnlyList<DraftStep> CreateInspectCommandSteps(JsonElement evt)
    {
        if (!TryGetString(evt, "command", out var command) || TryGetBool(evt, "ok") is false)
        {
            return [];
        }

        var data = evt.TryGetProperty("data", out var dataElement) && dataElement.ValueKind == JsonValueKind.Object
            ? dataElement
            : default;
        if (command is "telemetry_tail" or "telemetry_watch")
        {
            return CreateTelemetrySteps(data);
        }

        var step = command switch
        {
            "tap_text" => CreateTextStep(data, "tapText", "tap text"),
            "wait_visible" => CreateTextStep(data, "waitVisible", "wait visible"),
            "type_text" => CreateTextStep(data, "typeText", "type text"),
            "keyevent" => TryGetString(data, "code", out var code)
                ? new ScenarioStep("keyevent " + code, "keyevent", null, code, null)
                : null,
            "screenshot" or "take_screenshot" => CreateLabelStep(data, "takeScreenshot", "screenshot"),
            _ => null
        };

        return step is null ? [] : [new DraftStep(step, "inspect_command", "command_result", command, command, "medium")];
    }

    private static IReadOnlyList<DraftStep> CreateTelemetrySteps(JsonElement data)
    {
        if (data.ValueKind != JsonValueKind.Object)
        {
            return [];
        }

        var steps = new List<DraftStep>();
        if (data.TryGetProperty("events", out var events) && events.ValueKind == JsonValueKind.Array)
        {
            foreach (var telemetryEvent in events.EnumerateArray())
            {
                var step = CreateTelemetryStep(telemetryEvent);
                if (step is not null)
                {
                    steps.Add(new DraftStep(step, "telemetry", "command_result", "telemetry", step.Event ?? step.Step ?? step.Text, "medium"));
                }
            }
        }
        else
        {
            var step = CreateTelemetryStep(data);
            if (step is not null)
            {
                steps.Add(new DraftStep(step, "telemetry", "command_result", "telemetry", step.Event ?? step.Step ?? step.Text, "medium"));
            }
        }

        return steps;
    }

    private static ScenarioStep? CreateTelemetryStep(JsonElement telemetryEvent)
    {
        if (!TryGetString(telemetryEvent, "event", out var eventName))
        {
            return null;
        }

        if (string.Equals(eventName, "step", StringComparison.OrdinalIgnoreCase) &&
            TryGetString(telemetryEvent, "step", out var stepName))
        {
            return new ScenarioStep("wait step " + stepName, "waitStep", null, null, stepName, TimeoutSec: 15);
        }

        if (string.Equals(eventName, "action_ready", StringComparison.OrdinalIgnoreCase) &&
            TryGetString(telemetryEvent, "action", out var actionName))
        {
            TryGetString(telemetryEvent, "step", out var telemetryStepName);
            return new ScenarioStep("wait action " + actionName, "waitActionReady", actionName, null, string.IsNullOrWhiteSpace(telemetryStepName) ? null : telemetryStepName, TimeoutSec: 15);
        }

        return new ScenarioStep("assert event " + eventName, "assertEvent", null, null, null, Event: eventName, TimeoutSec: 15);
    }

    private static DraftStep? CreateScenarioStep(JsonElement evt, string eventType)
    {
        if (!TryGetString(evt, "action", out var action))
        {
            return null;
        }

        TryGetString(evt, "step", out var name);
        var stepName = name ?? action;
        return action switch
        {
            "waitVisible" or "waitNotVisible" or "tapText" or "typeText" or "waitLog" => TryGetString(evt, "text", out var text)
                ? new DraftStep(new ScenarioStep(stepName, action, text, null, null, TimeoutSec: action.StartsWith("wait", StringComparison.OrdinalIgnoreCase) ? 15 : null), "scenario_event", eventType, null, action + ": " + text, "high")
                : null,
            "keyevent" => TryGetString(evt, "code", out var code)
                ? new DraftStep(new ScenarioStep(stepName, action, null, code, null), "scenario_event", eventType, null, "keyevent: " + code, "high")
                : null,
            "waitStep" => TryGetString(evt, "step", out var waitStep)
                ? new DraftStep(new ScenarioStep(stepName, action, null, null, waitStep, TimeoutSec: 15), "scenario_event", eventType, null, "waitStep: " + waitStep, "high")
                : null,
            "takeScreenshot" => new DraftStep(new ScenarioStep(stepName, action, null, null, null, Label: stepName), "scenario_event", eventType, null, action, "high"),
            "captureArtifacts" => new DraftStep(new ScenarioStep(stepName, action, null, null, null, Label: stepName), "scenario_event", eventType, null, action, "high"),
            _ => null
        };
    }

    private static DraftStep? CreateScreenshotStep(JsonElement evt, string eventType)
    {
        var label = TryGetOptionalString(evt, "label") ?? "replay-screenshot";
        return new DraftStep(new ScenarioStep("capture " + label, "takeScreenshot", null, null, null, Label: label), "view_event", eventType, null, "screenshot: " + label, "medium");
    }

    private static DraftStep? CreateKeyCommandStep(JsonElement evt, string eventType)
    {
        if (!TryGetString(evt, "command", out var command))
        {
            return null;
        }

        return new DraftStep(new ScenarioStep("key command " + command, "keyevent", null, command, null), "view_event", eventType, null, "key command: " + command, "medium");
    }

    private static ScenarioStep? CreateTextStep(JsonElement data, string action, string fallbackName)
    {
        if (!TryGetString(data, "text", out var text))
        {
            return null;
        }

        return new ScenarioStep(fallbackName + " " + text, action, text, null, null, TimeoutSec: action.StartsWith("wait", StringComparison.OrdinalIgnoreCase) ? 15 : null);
    }

    private static ScenarioStep? CreateLabelStep(JsonElement data, string action, string fallbackLabel)
    {
        var label = TryGetOptionalString(data, "label") ?? fallbackLabel;
        return new ScenarioStep("capture " + label, action, null, null, null, Label: label);
    }

    private static IEnumerable<string> BuildWarnings(IReadOnlyList<ScenarioStep> steps)
    {
        if (steps.Any(static step => string.Equals(step.Action, "tapPoint", StringComparison.OrdinalIgnoreCase)))
        {
            yield return "Draft includes coordinate taps; add scenario metadata for device layout before using in CI.";
        }

        if (steps.All(static step => !string.Equals(step.Action, "waitVisible", StringComparison.OrdinalIgnoreCase)))
        {
            yield return "Draft has no waitVisible steps; add waits around asynchronous UI transitions.";
        }
    }

    private static IEnumerable<ReplayScenarioDraftSuggestion> BuildSuggestions(IReadOnlyList<ScenarioStep> steps)
    {
        for (var i = 0; i < steps.Count; i++)
        {
            var step = steps[i];
            if (string.Equals(step.Action, "tapText", StringComparison.OrdinalIgnoreCase))
            {
                yield return new ReplayScenarioDraftSuggestion(i + 1, "selector", "medium", "Review whether this tap should be preceded by waitVisible for the same text.");
            }
            else if (string.Equals(step.Action, "tapPoint", StringComparison.OrdinalIgnoreCase))
            {
                yield return new ReplayScenarioDraftSuggestion(i + 1, "coordinate", "low", "Replace coordinate tap with tapText or add layout metadata if possible.");
            }
            else if (string.Equals(step.Action, "takeScreenshot", StringComparison.OrdinalIgnoreCase))
            {
                yield return new ReplayScenarioDraftSuggestion(i + 1, "visual", "medium", "Consider upgrading screenshot capture to assertScreenshot with a baseline or region hash.");
            }
            else if (string.Equals(step.Action, "waitStep", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(step.Action, "waitActionReady", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(step.Action, "assertEvent", StringComparison.OrdinalIgnoreCase))
            {
                yield return new ReplayScenarioDraftSuggestion(i + 1, "telemetry", "medium", "Verify this semantic telemetry assertion is emitted reliably by the app before using it as a CI gate.");
            }
        }
    }

    private static bool TryGetString(JsonElement root, string name, out string value)
    {
        value = string.Empty;
        if (root.ValueKind != JsonValueKind.Object ||
            !root.TryGetProperty(name, out var property) ||
            property.ValueKind != JsonValueKind.String ||
            string.IsNullOrWhiteSpace(property.GetString()))
        {
            return false;
        }

        value = property.GetString()!;
        return true;
    }

    private static string? TryGetOptionalString(JsonElement root, string name) =>
        TryGetString(root, name, out var value) ? value : null;

    private static bool? TryGetBool(JsonElement root, string name)
    {
        if (root.ValueKind != JsonValueKind.Object ||
            !root.TryGetProperty(name, out var property) ||
            property.ValueKind is not JsonValueKind.True and not JsonValueKind.False)
        {
            return null;
        }

        return property.GetBoolean();
    }

    private sealed record DraftStep(
        ScenarioStep Step,
        string Source,
        string EventType,
        string? Command,
        string? Detail,
        string Confidence);
}
