using System.Linq;
using System.Text;
using System.Text.Json;
using Luotsi.Cli.Artifacts;
using Luotsi.Cli.Errors;
using Luotsi.Cli.Infrastructure.Contracts;
using Luotsi.Cli.Infrastructure.Serialization;
using Luotsi.Cli.Models;
using Luotsi.Cli.Scenarios;

namespace Luotsi.Cli.Cli.Replay;

internal sealed class ReplayScenarioDraftService(IFileSystem fileSystem, ScenarioValidationExecutorFactory validationExecutorFactory)
{
    private const string ScenarioDraftSummaryFileName = "scenario-draft-summary.json";
    private const string ScenarioDraftReviewFileName = "scenario-draft.md";
    private static readonly string[] PackagePropertyNames =
    [
        "package",
        "target_package",
        "targetPackage",
        "foreground_package",
        "foregroundPackage"
    ];

    private static readonly string[] FocusPropertyNames =
    [
        "current_focus",
        "currentFocus",
        "focus"
    ];

    private static readonly string[] PackageCarrierPropertyNames =
    [
        "data",
        "readiness",
        "preflight",
        "package_preflight",
        "packagePreflight",
        "device_allocation",
        "deviceAllocation",
        "state"
    ];

    private readonly IFileSystem _fileSystem = fileSystem ?? throw new ArgumentNullException(nameof(fileSystem));
    private readonly ScenarioValidationExecutorFactory _validationExecutorFactory = validationExecutorFactory ?? throw new ArgumentNullException(nameof(validationExecutorFactory));

    public async Task<ReplayScenarioDraftResult> CreateAsync(CliOptions options, ArtifactSession artifacts)
    {
        ArgumentNullException.ThrowIfNull(options);
        ArgumentNullException.ThrowIfNull(artifacts);

        var output = options.Get("output") ?? options.Get("file");
        var validate = options.HasFlag("validate");
        if (validate && string.IsNullOrWhiteSpace(output))
        {
            throw new UsageException("replay scenario-draft --validate requires --output <scenario.json> or --file <scenario.json>.");
        }

        var events = ReadTimelineEvents(artifacts.Root);
        var normalizationNotes = new List<ReplayScenarioDraftNormalization>();
        var draftSteps = NormalizeSteps(CreateSteps(events), normalizationNotes);
        if (draftSteps.Count == 0)
        {
            throw new UsageException("replay scenario-draft could not find action events in session-timeline.jsonl.");
        }

        var steps = draftSteps.Select(static step => step.Step).ToArray();
        var warnings = BuildWarnings(steps).ToArray();
        var packageProvenance = InferPackageProvenance(events);
        var deviceProvenance = InferDeviceProvenance(artifacts.Root);
        var jsonPath = options.HasFlag("write-json")
            ? Path.Join(artifacts.Root, ScenarioDraftSummaryFileName)
            : null;
        var markdownPath = options.HasFlag("write-markdown")
            ? Path.Join(artifacts.Root, ScenarioDraftReviewFileName)
            : null;
        var scenario = new ScenarioFile(
            options.Get("name") ?? "draft from replay",
            steps,
            Tags: ["draft", "generated", "replay"],
            Metadata: new ScenarioMetadata(
                Package: packageProvenance?.Package,
                Notes: $"Generated by `luotsi replay scenario-draft` from artifact root {artifacts.Root}. Review selectors, waits, and coordinate-specific steps before committing.",
                Device: deviceProvenance is null ? null : new ScenarioDeviceMetadata(Serial: deviceProvenance.Serial)));
        var suggestions = BuildSuggestions(steps).ToArray();
        var origins = draftSteps
            .Select((step, index) => new ReplayScenarioDraftStepOrigin(
                index + 1,
                step.Source,
                step.EventType,
                step.Command,
                step.Detail,
                step.Confidence,
                step.SourcePath,
                step.Sequence,
                step.Timestamp,
                BuildSourceCommand(step.SourcePath, step.Sequence)))
            .ToArray();
        var sourceSummaries = BuildSourceSummaries(origins, normalizationNotes).ToArray();
        var reviewItems = BuildReviewItems(warnings, suggestions, origins, normalizationNotes).ToList();
        ReplayScenarioDraftValidation? validation = null;

        if (!string.IsNullOrWhiteSpace(output))
        {
            var directory = Path.GetDirectoryName(output);
            if (!string.IsNullOrWhiteSpace(directory))
            {
                _fileSystem.CreateDirectory(directory);
            }

            await _fileSystem.WriteAllTextAsync(output, JsonSerializer.Serialize(scenario, AppJson.Options) + Environment.NewLine, new UTF8Encoding(false)).ConfigureAwait(false);

            if (validate)
            {
                validation = await ValidateDraftAsync(output).ConfigureAwait(false);
            }
        }

        if (validation is { Status: "failed" } && !string.IsNullOrWhiteSpace(validation.Error))
        {
            reviewItems.Insert(0, new ReplayScenarioDraftReviewItem(
                "error",
                "validation",
                null,
                validation.Error,
                validation.Command));
        }

        var confidence = warnings.Length == 0 && !string.Equals(validation?.Status, "failed", StringComparison.OrdinalIgnoreCase)
            ? "medium"
            : "low";
        var runHandoff = BuildRunHandoff(output, validation, scenario);
        var nextActions = BuildNextActions(output, artifacts.Root, jsonPath, origins, reviewItems, normalizationNotes, validation, runHandoff).ToArray();
        var result = new ReplayScenarioDraftResult(
            ResultSchemas.ScenarioDraft,
            artifacts.Root,
            output,
            jsonPath,
            markdownPath,
            confidence,
            warnings,
            scenario,
            suggestions,
            reviewItems,
            sourceSummaries,
            origins,
            normalizationNotes,
            packageProvenance,
            deviceProvenance,
            validation,
            runHandoff,
            nextActions,
            BuildCommandHints(output, artifacts.Root, jsonPath, markdownPath, origins, validation, runHandoff).ToArray());

        if (jsonPath is not null)
        {
            await artifacts.WriteJsonAsync(ScenarioDraftSummaryFileName, result).ConfigureAwait(false);
        }

        if (markdownPath is not null)
        {
            await artifacts.WriteTextAsync(ScenarioDraftReviewFileName, BuildMarkdown(result)).ConfigureAwait(false);
        }

        return result;
    }

    private async Task<ReplayScenarioDraftValidation> ValidateDraftAsync(string output)
    {
        var command = BuildValidateCommand(output);
        try
        {
            _ = await _validationExecutorFactory.Create().ValidateFileAsync(output).ConfigureAwait(false);
            return new ReplayScenarioDraftValidation("validated", command, Message: "Static scenario validation passed.");
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            return new ReplayScenarioDraftValidation("failed", command, Error: ex.Message);
        }
    }

    private static IReadOnlyList<DraftStep> NormalizeSteps(
        IReadOnlyList<DraftStep> steps,
        ICollection<ReplayScenarioDraftNormalization> normalizations)
    {
        var normalized = new List<DraftStep>();
        foreach (var step in steps)
        {
            if (TryCreateDuplicateWaitNormalization(normalized, step, out var normalization))
            {
                normalizations.Add(normalization);
                continue;
            }

            if (TryCreatePreTapWaitNormalization(normalized, step, out var waitStep, out normalization))
            {
                normalizations.Add(normalization);
                normalized.Add(waitStep);
            }

            normalized.Add(step);
        }

        return normalized;
    }

    private static bool TryCreateDuplicateWaitNormalization(
        IReadOnlyList<DraftStep> normalized,
        DraftStep candidate,
        out ReplayScenarioDraftNormalization normalization)
    {
        normalization = null!;
        var candidateKey = GetWaitKey(candidate.Step);
        if (candidateKey is null)
        {
            return false;
        }

        var previous = normalized.LastOrDefault();
        if (previous is null || !string.Equals(GetWaitKey(previous.Step), candidateKey, StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        normalization = new ReplayScenarioDraftNormalization(
            "duplicate_wait",
            $"Dropped adjacent duplicate {candidate.Step.Action} for `{GetStepTarget(candidate.Step)}`.",
            candidate.Source,
            candidate.EventType,
            candidate.Confidence,
            candidate.SourcePath,
            candidate.Sequence,
            candidate.Timestamp,
            BuildSourceCommand(candidate.SourcePath, candidate.Sequence));
        return true;
    }

    private static bool TryCreatePreTapWaitNormalization(
        IReadOnlyList<DraftStep> normalized,
        DraftStep candidate,
        out DraftStep waitStep,
        out ReplayScenarioDraftNormalization normalization)
    {
        waitStep = null!;
        normalization = null!;

        var wait = CreatePreTapWaitStep(candidate.Step);
        var waitKey = wait is null ? null : GetWaitKey(wait);
        if (wait is null || waitKey is null)
        {
            return false;
        }

        var previous = normalized.LastOrDefault();
        if (previous is not null && string.Equals(GetWaitKey(previous.Step), waitKey, StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        var target = GetStepTarget(candidate.Step);
        waitStep = candidate with
        {
            Step = wait,
            Detail = $"inserted {wait.Action} before {candidate.Step.Action}: {target}"
        };
        normalization = new ReplayScenarioDraftNormalization(
            "inserted_pre_tap_wait",
            $"Inserted {wait.Action} before {candidate.Step.Action} for `{target}`.",
            candidate.Source,
            candidate.EventType,
            candidate.Confidence,
            candidate.SourcePath,
            candidate.Sequence,
            candidate.Timestamp,
            BuildSourceCommand(candidate.SourcePath, candidate.Sequence));
        return true;
    }

    private static ScenarioStep? CreatePreTapWaitStep(ScenarioStep step) =>
        step.Action switch
        {
            "tapText" when !string.IsNullOrWhiteSpace(step.Text) =>
                new ScenarioStep("wait for " + step.Text, "waitVisible", step.Text, null, null, TimeoutSec: 15),
            "tapElement" when step.Selector is not null =>
                new ScenarioStep("wait for " + GetStepTarget(step), "waitElement", null, null, null, TimeoutSec: 15, Selector: step.Selector),
            _ => null
        };

    private static string? GetWaitKey(ScenarioStep step) =>
        step.Action switch
        {
            "waitVisible" when !string.IsNullOrWhiteSpace(step.Text) => "waitVisible:" + step.Text,
            "waitElement" when step.Selector is not null => "waitElement:" + step.Selector.Describe(),
            "waitStep" when !string.IsNullOrWhiteSpace(step.Step) => "waitStep:" + step.Step,
            "waitActionReady" when !string.IsNullOrWhiteSpace(step.Text) => "waitActionReady:" + step.Step + ":" + step.Text,
            "assertEvent" when !string.IsNullOrWhiteSpace(step.Event) => "assertEvent:" + step.Event,
            _ => null
        };

    private static string GetStepTarget(ScenarioStep step) =>
        step.Text ?? step.Selector?.Describe() ?? step.Step ?? step.Event ?? step.Code ?? step.Label ?? step.Action;

    private static IEnumerable<ReplayScenarioDraftSourceSummary> BuildSourceSummaries(
        IReadOnlyList<ReplayScenarioDraftStepOrigin> origins,
        IReadOnlyList<ReplayScenarioDraftNormalization> normalizations)
    {
        var sources = origins
            .Select(static origin => origin.Source)
            .Concat(normalizations.Select(static normalization => normalization.Source))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(static source => source, StringComparer.OrdinalIgnoreCase);

        foreach (var source in sources)
        {
            var sourceOrigins = origins
                .Where(origin => string.Equals(origin.Source, source, StringComparison.OrdinalIgnoreCase))
                .ToArray();
            var sourceNormalizations = normalizations.Count(normalization =>
                string.Equals(normalization.Source, source, StringComparison.OrdinalIgnoreCase));
            var eventTypes = sourceOrigins
                .Select(static origin => origin.EventType)
                .Concat(normalizations
                    .Where(normalization => string.Equals(normalization.Source, source, StringComparison.OrdinalIgnoreCase))
                    .Select(static normalization => normalization.EventType))
                .Where(static eventType => !string.IsNullOrWhiteSpace(eventType))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderBy(static eventType => eventType, StringComparer.OrdinalIgnoreCase)
                .ToArray();

            yield return new ReplayScenarioDraftSourceSummary(
                source,
                sourceOrigins.Length,
                sourceNormalizations,
                eventTypes,
                SummarizeConfidence(sourceOrigins.Select(static origin => origin.Confidence)
                    .Concat(normalizations
                        .Where(normalization => string.Equals(normalization.Source, source, StringComparison.OrdinalIgnoreCase))
                        .Select(static normalization => normalization.Confidence))));
        }
    }

    private static string SummarizeConfidence(IEnumerable<string> confidenceValues)
    {
        var values = confidenceValues.ToArray();
        if (values.Any(static value => string.Equals(value, "low", StringComparison.OrdinalIgnoreCase)))
        {
            return "low";
        }

        if (values.Any(static value => string.Equals(value, "medium", StringComparison.OrdinalIgnoreCase)))
        {
            return "medium";
        }

        return values.Length == 0 ? "unknown" : "high";
    }

    private static string BuildMarkdown(ReplayScenarioDraftResult result)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Luotsi Scenario Draft");
        builder.AppendLine();
        builder.AppendLine($"Artifact root: `{result.ArtifactRoot}`");
        builder.AppendLine($"Scenario: `{result.Scenario.Name}`");
        builder.AppendLine($"Output: `{result.Output ?? "(not written)"}`");
        builder.AppendLine($"Confidence: `{result.Confidence}`");
        builder.AppendLine($"Steps: `{result.Scenario.Steps.Count}`");
        if (result.Validation is not null)
        {
            builder.AppendLine();
            builder.AppendLine("## Validation");
            builder.AppendLine();
            builder.AppendLine($"- Status: `{EscapeMarkdown(result.Validation.Status)}`");
            builder.AppendLine($"- Command: `{EscapeMarkdown(result.Validation.Command)}`");
            if (!string.IsNullOrWhiteSpace(result.Validation.Message))
            {
                builder.AppendLine($"- Message: {EscapeMarkdown(result.Validation.Message)}");
            }

            if (!string.IsNullOrWhiteSpace(result.Validation.Error))
            {
                builder.AppendLine($"- Error: {EscapeMarkdown(result.Validation.Error)}");
            }
        }

        if (result.PackageProvenance is not null)
        {
            builder.AppendLine();
            builder.AppendLine("## Package Provenance");
            builder.AppendLine();
            builder.AppendLine($"- Package: `{EscapeMarkdown(result.PackageProvenance.Package)}`");
            builder.AppendLine($"- Source: `{EscapeMarkdown(result.PackageProvenance.Source)}`");
            builder.AppendLine($"- Event: `{EscapeMarkdown(result.PackageProvenance.EventType)}`");
            if (!string.IsNullOrWhiteSpace(result.PackageProvenance.Command))
            {
                builder.AppendLine($"- Command: `{EscapeMarkdown(result.PackageProvenance.Command)}`");
            }

            if (!string.IsNullOrWhiteSpace(result.PackageProvenance.SourcePath) && result.PackageProvenance.Sequence is { } sequence)
            {
                builder.AppendLine($"- Timeline: `{EscapeMarkdown(result.PackageProvenance.SourcePath)}:{sequence}`");
            }

            if (!string.IsNullOrWhiteSpace(result.PackageProvenance.SourceCommand))
            {
                builder.AppendLine($"- Reopen: `{EscapeMarkdown(result.PackageProvenance.SourceCommand)}`");
            }
        }

        if (result.DeviceProvenance is not null)
        {
            builder.AppendLine();
            builder.AppendLine("## Device Provenance");
            builder.AppendLine();
            builder.AppendLine($"- Serial: `{EscapeMarkdown(result.DeviceProvenance.Serial)}`");
            builder.AppendLine($"- Source: `{EscapeMarkdown(result.DeviceProvenance.Source)}`");
            builder.AppendLine($"- Session: `{EscapeMarkdown(result.DeviceProvenance.SessionKind)}`");
            if (!string.IsNullOrWhiteSpace(result.DeviceProvenance.SessionId))
            {
                builder.AppendLine($"- Session id: `{EscapeMarkdown(result.DeviceProvenance.SessionId)}`");
            }

            if (!string.IsNullOrWhiteSpace(result.DeviceProvenance.SourcePath))
            {
                builder.AppendLine($"- Metadata: `{EscapeMarkdown(result.DeviceProvenance.SourcePath)}`");
            }
        }

        if (result.RunHandoff is not null)
        {
            builder.AppendLine();
            builder.AppendLine("## Run Handoff");
            builder.AppendLine();
            builder.AppendLine($"- Status: `{EscapeMarkdown(result.RunHandoff.Status)}`");
            builder.AppendLine($"- Reason: {EscapeMarkdown(result.RunHandoff.Reason)}");
            if (!string.IsNullOrWhiteSpace(result.RunHandoff.DryRunCommand))
            {
                builder.AppendLine($"- Dry run: `{EscapeMarkdown(result.RunHandoff.DryRunCommand)}`");
            }

            if (!string.IsNullOrWhiteSpace(result.RunHandoff.PreflightCommand))
            {
                builder.AppendLine($"- Preflight: `{EscapeMarkdown(result.RunHandoff.PreflightCommand)}`");
            }

            if (!string.IsNullOrWhiteSpace(result.RunHandoff.ClaimedRunCommand))
            {
                builder.AppendLine($"- Claimed run: `{EscapeMarkdown(result.RunHandoff.ClaimedRunCommand)}`");
            }

            if (!string.IsNullOrWhiteSpace(result.RunHandoff.RunCommand))
            {
                builder.AppendLine($"- Run: `{EscapeMarkdown(result.RunHandoff.RunCommand)}`");
            }
        }

        builder.AppendLine();
        builder.AppendLine("## Warnings");
        builder.AppendLine();
        if (result.Warnings.Count == 0)
        {
            builder.AppendLine("- None");
        }
        else
        {
            foreach (var warning in result.Warnings)
            {
                builder.AppendLine("- " + warning);
            }
        }

        builder.AppendLine();
        builder.AppendLine("## Suggestions");
        builder.AppendLine();
        if (result.Suggestions.Count == 0)
        {
            builder.AppendLine("- None");
        }
        else
        {
            foreach (var suggestion in result.Suggestions)
            {
                builder.AppendLine($"- Step {suggestion.StepIndex}: `{suggestion.Kind}` ({suggestion.Confidence}) - {suggestion.Message}");
            }
        }

        builder.AppendLine();
        builder.AppendLine("## Review Checklist");
        builder.AppendLine();
        if (result.ReviewItems.Count == 0)
        {
            builder.AppendLine("- None");
        }
        else
        {
            foreach (var item in result.ReviewItems)
            {
                var step = item.StepIndex is null ? string.Empty : $" step {item.StepIndex}:";
                var command = string.IsNullOrWhiteSpace(item.Command) ? string.Empty : $" `{item.Command}`";
                builder.AppendLine($"- `{item.Severity}` `{item.Category}`{step} {item.Message}{command}");
            }
        }

        builder.AppendLine();
        builder.AppendLine("## Recommended Next Actions");
        builder.AppendLine();
        if (result.NextActions.Count == 0)
        {
            builder.AppendLine("- None");
        }
        else
        {
            foreach (var action in result.NextActions)
            {
                builder.AppendLine($"- `{action.Kind}` {action.Title}: {action.Reason} `{action.Command}`");
            }
        }

        builder.AppendLine();
        builder.AppendLine("## Next Commands");
        builder.AppendLine();
        foreach (var command in result.SuggestedCommands)
        {
            builder.AppendLine($"- `{command.Command}`");
            builder.AppendLine($"  {command.Purpose}");
        }

        builder.AppendLine();
        builder.AppendLine("## Source Summary");
        builder.AppendLine();
        builder.AppendLine("| Source | Steps | Normalizations | Events | Confidence |");
        builder.AppendLine("|---|---:|---:|---|---|");
        foreach (var summary in result.SourceSummaries)
        {
            builder.Append("| ");
            builder.Append(EscapeMarkdown(summary.Source));
            builder.Append(" | ");
            builder.Append(summary.StepCount);
            builder.Append(" | ");
            builder.Append(summary.NormalizationCount);
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(string.Join(", ", summary.EventTypes)));
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(summary.Confidence));
            builder.AppendLine(" |");
        }

        builder.AppendLine();
        builder.AppendLine("## Normalizations");
        builder.AppendLine();
        if (result.Normalizations.Count == 0)
        {
            builder.AppendLine("- None");
        }
        else
        {
            foreach (var normalization in result.Normalizations)
            {
                var location = string.IsNullOrWhiteSpace(normalization.SourcePath)
                    ? string.Empty
                    : $" at `{normalization.SourcePath}:{normalization.Sequence}`";
                builder.AppendLine($"- `{normalization.Kind}` ({normalization.Confidence}) from `{normalization.Source}`{location}: {normalization.Detail}");
            }
        }

        builder.AppendLine();
        builder.AppendLine("## Step Origins");
        builder.AppendLine();
        builder.AppendLine("| # | Source | File | Seq | Event | Command | Confidence | Detail | Reopen |");
        builder.AppendLine("|---:|---|---|---:|---|---|---|---|---|");
        foreach (var origin in result.StepOrigins)
        {
            builder.Append("| ");
            builder.Append(origin.StepIndex);
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(origin.Source));
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(origin.SourcePath ?? string.Empty));
            builder.Append(" | ");
            builder.Append(origin.Sequence?.ToString(System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty);
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(origin.EventType));
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(origin.Command ?? string.Empty));
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(origin.Confidence));
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(origin.Detail ?? string.Empty));
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(origin.SourceCommand ?? string.Empty));
            builder.AppendLine(" |");
        }

        builder.AppendLine();
        builder.AppendLine("## Draft Steps");
        builder.AppendLine();
        builder.AppendLine("| # | Action | Name | Text/Code/Label |");
        builder.AppendLine("|---:|---|---|---|");
        for (var i = 0; i < result.Scenario.Steps.Count; i++)
        {
            var step = result.Scenario.Steps[i];
            builder.Append("| ");
            builder.Append(i + 1);
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(step.Action));
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(step.Name ?? string.Empty));
            builder.Append(" | ");
            builder.Append(EscapeMarkdown(GetStepTarget(step)));
            builder.AppendLine(" |");
        }

        return builder.ToString();
    }

    private static IEnumerable<ReplayScenarioDraftNextAction> BuildNextActions(
        string? output,
        string artifactRoot,
        string? jsonPath,
        IReadOnlyList<ReplayScenarioDraftStepOrigin> origins,
        IReadOnlyList<ReplayScenarioDraftReviewItem> reviewItems,
        IReadOnlyList<ReplayScenarioDraftNormalization> normalizations,
        ReplayScenarioDraftValidation? validation,
        ReplayScenarioDraftRunHandoff? runHandoff)
    {
        var reviewReason = reviewItems.Count == 0 && normalizations.Count == 0
            ? "Confirm the generated scenario flow and source provenance before editing."
            : $"Review {reviewItems.Count} checklist item(s) and {normalizations.Count} normalization(s) before editing.";
        yield return new ReplayScenarioDraftNextAction(
            "review_draft",
            "Review generated draft",
            reviewReason,
            $"luotsi replay open --artifacts {Quote(artifactRoot)}");

        var validationPassed = string.Equals(validation?.Status, "validated", StringComparison.OrdinalIgnoreCase);
        if (!string.IsNullOrWhiteSpace(output) && !validationPassed)
        {
            var reason = string.Equals(validation?.Status, "failed", StringComparison.OrdinalIgnoreCase)
                ? "Resolve the static validation failure before committing or running the draft."
                : "Run static scenario validation before committing or running the draft.";
            yield return new ReplayScenarioDraftNextAction(
                "validate_scenario",
                "Validate generated scenario",
                reason,
                BuildValidateCommand(output));
        }

        if (validationPassed && !string.IsNullOrWhiteSpace(output))
        {
            yield return new ReplayScenarioDraftNextAction(
                "dry_run_scenario",
                "Plan scenario run",
                "Confirm the generated scenario is selected as expected before starting a device run.",
                BuildDryRunCommand(output));

            if (!string.IsNullOrWhiteSpace(runHandoff?.PreflightCommand))
            {
                yield return new ReplayScenarioDraftNextAction(
                    "preflight_device",
                    "Preflight target device",
                    "Verify adb/device/app readiness before executing the generated scenario.",
                    runHandoff.PreflightCommand);
            }
        }

        if (!string.IsNullOrWhiteSpace(jsonPath))
        {
            yield return new ReplayScenarioDraftNextAction(
                "audit_provenance",
                "Audit draft provenance",
                "Use the graph to inspect generated steps, draft normalizations, source families, and timeline links.",
                $"luotsi replay graph --artifacts {Quote(artifactRoot)} --node-kind scenario_draft --write-markdown");
        }

        var firstOrigin = origins.FirstOrDefault(static origin => !string.IsNullOrWhiteSpace(origin.SourceCommand));
        if (!string.IsNullOrWhiteSpace(firstOrigin?.SourceCommand))
        {
            yield return new ReplayScenarioDraftNextAction(
                "reopen_source_event",
                "Reopen first source event",
                "Inspect the timeline event that produced the first generated draft step.",
                firstOrigin.SourceCommand);
        }
    }

    private static IEnumerable<ReplayScenarioDraftCommandHint> BuildCommandHints(
        string? output,
        string artifactRoot,
        string? jsonPath,
        string? markdownPath,
        IReadOnlyList<ReplayScenarioDraftStepOrigin> origins,
        ReplayScenarioDraftValidation? validation,
        ReplayScenarioDraftRunHandoff? runHandoff)
    {
        yield return new ReplayScenarioDraftCommandHint(
            $"luotsi replay packet --artifacts {Quote(artifactRoot)}",
            "Write the durable first-minute packet before editing or sharing the generated draft.");

        yield return new ReplayScenarioDraftCommandHint(
            $"luotsi replay packet --artifacts {Quote(artifactRoot)} --check",
            "Validate the durable packet before handoff or deeper replay.");

        yield return new ReplayScenarioDraftCommandHint(
            $"luotsi replay open --artifacts {Quote(artifactRoot)}",
            "Open the artifact browser for screenshots, timelines, and generated draft review files.");

        yield return new ReplayScenarioDraftCommandHint(
            $"luotsi replay capsule --artifacts {Quote(artifactRoot)} --write-readme --write-json",
            "Write the replay capsule that links the draft to failures, artifacts, and follow-up commands.");

        yield return new ReplayScenarioDraftCommandHint(
            $"luotsi replay scrub --artifacts {Quote(artifactRoot)} --context 3 --write-markdown",
            "Write a scrub view around the same evidence before editing the draft.");

        if (!string.IsNullOrWhiteSpace(jsonPath))
        {
            yield return new ReplayScenarioDraftCommandHint(
                $"luotsi replay graph --artifacts {Quote(artifactRoot)} --node-kind scenario_draft --write-markdown",
                "Audit draft provenance, generated steps, and normalizations in the semantic graph.");
        }

        var validationPassed = string.Equals(validation?.Status, "validated", StringComparison.OrdinalIgnoreCase);
        if (!string.IsNullOrWhiteSpace(output) && !validationPassed)
        {
            yield return new ReplayScenarioDraftCommandHint(
                BuildValidateCommand(output),
                "Validate the generated scenario before committing or running it.");
        }

        if (runHandoff is not null &&
            string.Equals(runHandoff.Status, "ready", StringComparison.OrdinalIgnoreCase) &&
            !string.IsNullOrWhiteSpace(runHandoff.PreflightCommand) &&
            !string.IsNullOrWhiteSpace(runHandoff.DryRunCommand) &&
            !string.IsNullOrWhiteSpace(runHandoff.RunCommand))
        {
            yield return new ReplayScenarioDraftCommandHint(
                runHandoff.DryRunCommand,
                "Plan the generated scenario without starting a device run.");

            yield return new ReplayScenarioDraftCommandHint(
                runHandoff.PreflightCommand,
                "Check the selected device and target app before executing the generated scenario.");

            if (!string.IsNullOrWhiteSpace(runHandoff.ClaimedRunCommand))
            {
                yield return new ReplayScenarioDraftCommandHint(
                    runHandoff.ClaimedRunCommand,
                    "Claim the selected device before running the generated scenario in a shared lab.");
            }

            yield return new ReplayScenarioDraftCommandHint(
                runHandoff.RunCommand,
                "Run the generated scenario on a selected device after review.");
        }

        if (!string.IsNullOrWhiteSpace(markdownPath))
        {
            yield return new ReplayScenarioDraftCommandHint(
                $"luotsi replay search --artifacts {Quote(artifactRoot)} --contains \"Review Checklist\"",
                "Find the generated review checklist in replay artifacts.");
        }

        var firstOrigin = origins.FirstOrDefault(static origin => !string.IsNullOrWhiteSpace(origin.SourceCommand));
        if (!string.IsNullOrWhiteSpace(firstOrigin?.SourceCommand))
        {
            yield return new ReplayScenarioDraftCommandHint(
                firstOrigin.SourceCommand,
                "Reopen the first generated step's source timeline event.");
        }
    }

    private static string EscapeMarkdown(string value) =>
        value.Replace("|", "\\|", StringComparison.Ordinal)
            .Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal);

    private static ReplayScenarioDraftPackageProvenance? InferPackageProvenance(IReadOnlyList<DraftTimelineEvent> events)
    {
        foreach (var timelineEvent in events)
        {
            var evt = timelineEvent.Element;
            if (TryFindPackageCandidate(evt, string.Empty, out var package, out var source))
            {
                TryGetString(evt, "type", out var eventType);
                TryGetString(evt, "command", out var command);
                return new ReplayScenarioDraftPackageProvenance(
                    package,
                    source,
                    string.IsNullOrWhiteSpace(eventType) ? "timeline_event" : eventType,
                    string.IsNullOrWhiteSpace(command) ? null : command,
                    timelineEvent.SourcePath,
                    timelineEvent.Sequence,
                    timelineEvent.Timestamp,
                    BuildSourceCommand(timelineEvent.SourcePath, timelineEvent.Sequence));
            }
        }

        return null;
    }

    private ReplayScenarioDraftDeviceProvenance? InferDeviceProvenance(string artifactRoot)
    {
        var files = _fileSystem.GetFiles(artifactRoot, SessionReplayArtifacts.MetadataFileName, SearchOption.AllDirectories);
        var candidates = files
            .Order(StringComparer.OrdinalIgnoreCase)
            .Select(file => TryReadDeviceProvenance(artifactRoot, file))
            .Where(static candidate => candidate is not null)
            .Select(static candidate => candidate!)
            .ToArray();

        return candidates
            .Select(static candidate => candidate.Serial)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Take(2)
            .Count() == 1
                ? candidates[0]
                : null;
    }

    private ReplayScenarioDraftDeviceProvenance? TryReadDeviceProvenance(string artifactRoot, string file)
    {
        try
        {
            using var stream = _fileSystem.OpenRead(file);
            using var document = JsonDocument.Parse(stream);
            var root = document.RootElement;
            if (root.ValueKind != JsonValueKind.Object ||
                !TryGetString(root, "schema", out var schema) ||
                !string.Equals(schema, ResultSchemas.SessionReplay, StringComparison.Ordinal) ||
                !TryGetString(root, "target", out var target) ||
                !IsLikelyAdbSerial(target))
            {
                return null;
            }

            return new ReplayScenarioDraftDeviceProvenance(
                target.Trim(),
                "session_replay.target",
                TryGetString(root, "sessionKind", out var sessionKind) ? sessionKind : "replay",
                TryGetString(root, "sessionId", out var sessionId) ? sessionId : null,
                Path.GetRelativePath(artifactRoot, file).Replace('\\', '/'),
                TryReadTimestamp(root));
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or JsonException or FormatException)
        {
            return null;
        }
    }

    private static bool TryFindPackageCandidate(JsonElement root, string source, out string package, out string packageSource)
    {
        package = string.Empty;
        packageSource = string.Empty;
        if (root.ValueKind != JsonValueKind.Object)
        {
            return false;
        }

        var packageCandidate = PackagePropertyNames
            .Select(name => (Name: name, Value: TryGetString(root, name, out var value) ? value : null))
            .Where(candidate => candidate.Value is not null && IsLikelyAndroidPackage(candidate.Value))
            .FirstOrDefault();
        if (packageCandidate.Value is not null)
        {
            package = packageCandidate.Value.Trim();
            packageSource = BuildPackageSource(source, packageCandidate.Name);
            return true;
        }

        var focusCandidate = FocusPropertyNames
            .Select(name =>
            {
                var focusedPackage = string.Empty;
                var found = TryGetString(root, name, out var focus) &&
                    TryParsePackageFromFocus(focus, out focusedPackage);
                return (Name: name, Package: found ? focusedPackage : null);
            })
            .Where(candidate => candidate.Package is not null)
            .FirstOrDefault();
        if (focusCandidate.Package is not null)
        {
            package = focusCandidate.Package;
            packageSource = BuildPackageSource(source, focusCandidate.Name);
            return true;
        }

        var nestedPackageCarrierProperties = root.EnumerateObject()
            .Where(property => property.Value.ValueKind == JsonValueKind.Object &&
                PackageCarrierPropertyNames.Contains(property.Name, StringComparer.Ordinal));
        var nestedPackageCandidate = nestedPackageCarrierProperties
            .Select(property =>
            {
                var nestedPackage = string.Empty;
                var nestedPackageSource = string.Empty;
                var found = TryFindPackageCandidate(
                    property.Value,
                    BuildPackageSource(source, property.Name),
                    out nestedPackage,
                    out nestedPackageSource);
                return (Found: found, Package: nestedPackage, PackageSource: nestedPackageSource);
            })
            .Where(candidate => candidate.Found)
            .FirstOrDefault();
        if (nestedPackageCandidate.Found)
        {
            package = nestedPackageCandidate.Package;
            packageSource = nestedPackageCandidate.PackageSource;
            return true;
        }

        return false;
    }

    private static string BuildPackageSource(string source, string propertyName) =>
        string.IsNullOrWhiteSpace(source) ? propertyName : source + "." + propertyName;

    private static bool TryParsePackageFromFocus(string value, out string package)
    {
        package = string.Empty;
        var slash = value.IndexOf('/', StringComparison.Ordinal);
        if (slash <= 0)
        {
            return false;
        }

        var start = slash - 1;
        while (start >= 0 && !char.IsWhiteSpace(value[start]) && value[start] is not '{' and not '}')
        {
            start--;
        }

        var candidate = value[(start + 1)..slash];
        var colon = candidate.LastIndexOf(':');
        if (colon >= 0 && colon + 1 < candidate.Length)
        {
            candidate = candidate[(colon + 1)..];
        }

        if (!IsLikelyAndroidPackage(candidate))
        {
            return false;
        }

        package = candidate.Trim();
        return true;
    }

    private static bool IsLikelyAndroidPackage(string value)
    {
        var candidate = value.Trim();
        return !string.IsNullOrWhiteSpace(candidate) &&
            candidate.Contains(".", StringComparison.Ordinal) &&
            !candidate.StartsWith(".", StringComparison.Ordinal) &&
            !candidate.EndsWith(".", StringComparison.Ordinal) &&
            !candidate.Contains("..", StringComparison.Ordinal) &&
            !candidate.Contains("/", StringComparison.Ordinal) &&
            !candidate.Contains("\\", StringComparison.Ordinal) &&
            !candidate.Contains("<", StringComparison.Ordinal) &&
            !candidate.Contains(">", StringComparison.Ordinal) &&
            !candidate.Contains("{", StringComparison.Ordinal) &&
            !candidate.Contains("}", StringComparison.Ordinal) &&
            !candidate.Contains("$", StringComparison.Ordinal) &&
            !candidate.Contains(":", StringComparison.Ordinal) &&
            !candidate.EndsWith(".apk", StringComparison.OrdinalIgnoreCase) &&
            candidate.Any(static ch => char.IsLetter(ch)) &&
            candidate.All(static ch => char.IsLetterOrDigit(ch) || ch is '_' or '.') &&
            candidate.Split('.', StringSplitOptions.RemoveEmptyEntries).Length >= 2;
    }

    private static bool IsLikelyAdbSerial(string value)
    {
        var candidate = value.Trim();
        if (string.IsNullOrWhiteSpace(candidate) ||
            candidate.Length < 3 ||
            candidate.Any(char.IsWhiteSpace) ||
            candidate.Contains("<", StringComparison.Ordinal) ||
            candidate.Contains(">", StringComparison.Ordinal) ||
            candidate.Contains("{", StringComparison.Ordinal) ||
            candidate.Contains("}", StringComparison.Ordinal) ||
            candidate.Contains("$", StringComparison.Ordinal) ||
            candidate.Contains("/", StringComparison.Ordinal) ||
            candidate.Contains("\\", StringComparison.Ordinal))
        {
            return false;
        }

        var colon = candidate.LastIndexOf(':');
        if (colon >= 0)
        {
            var host = candidate[..colon];
            var port = candidate[(colon + 1)..];
            return !string.IsNullOrWhiteSpace(host) &&
                port.Length > 0 &&
                port.All(char.IsDigit) &&
                host.All(static ch => char.IsLetterOrDigit(ch) || ch is '.' or '_' or '-');
        }

        if (candidate.Contains(".", StringComparison.Ordinal))
        {
            return false;
        }

        return candidate.Any(char.IsLetterOrDigit) &&
            candidate.All(static ch => char.IsLetterOrDigit(ch) || ch is '_' or '-');
    }

    private IReadOnlyList<DraftTimelineEvent> ReadTimelineEvents(string artifactRoot)
    {
        var files = _fileSystem.GetFiles(artifactRoot, SessionReplayArtifacts.TimelineFileName, SearchOption.AllDirectories);
        if (files.Count == 0)
        {
            throw new UsageException($"No {SessionReplayArtifacts.TimelineFileName} was found under artifact root '{artifactRoot}'.");
        }

        return files.Order(StringComparer.OrdinalIgnoreCase)
            .SelectMany(file => ReadTimelineEventsFromFile(artifactRoot, file))
            .ToArray();
    }

    private IEnumerable<DraftTimelineEvent> ReadTimelineEventsFromFile(string artifactRoot, string file)
    {
        using var stream = _fileSystem.OpenRead(file);
        using var reader = new StreamReader(stream, Encoding.UTF8, detectEncodingFromByteOrderMarks: true, bufferSize: 4096);
        var sequence = 0;
        while (reader.ReadLine() is { } line)
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }

            var evt = ParseTimelineEvent(file, line);
            if (evt is not null)
            {
                yield return new DraftTimelineEvent(
                    Path.GetRelativePath(artifactRoot, file).Replace('\\', '/'),
                    sequence,
                    TryReadTimestamp(evt.Value),
                    evt.Value);
            }

            sequence++;
        }
    }

    private static JsonElement? ParseTimelineEvent(string file, string line)
    {
        try
        {
            using var document = JsonDocument.Parse(line);
            return document.RootElement.ValueKind == JsonValueKind.Object
                ? document.RootElement.Clone()
                : null;
        }
        catch (JsonException ex)
        {
            throw new UsageException($"replay scenario-draft encountered invalid JSON in '{file}'. {ex.Message} Line: {line}");
        }
    }

    private static IReadOnlyList<DraftStep> CreateSteps(IReadOnlyList<DraftTimelineEvent> events)
    {
        var steps = new List<DraftStep>();
        foreach (var timelineEvent in events)
        {
            var evt = timelineEvent.Element;
            if (!TryGetString(evt, "type", out var type))
            {
                continue;
            }

            if (string.Equals(type, "command_result", StringComparison.Ordinal))
            {
                steps.AddRange(CreateInspectCommandSteps(evt).Select(timelineEvent.Attach));
                continue;
            }

            if (string.Equals(type, "screen_delta", StringComparison.Ordinal))
            {
                steps.AddRange(CreateScreenDeltaSteps(evt).Select(timelineEvent.Attach));
                continue;
            }

            var step = type switch
            {
                "scenario_step_passed" or "scenario_step_continued_on_error" or "scenario_step_failed" => CreateScenarioStep(evt, type),
                "view_screenshot_captured" => CreateScreenshotStep(evt, type),
                "view_key_command_sent" => CreateKeyCommandStep(evt, type),
                _ => null
            };

            if (step is not null)
            {
                steps.Add(timelineEvent.Attach(step));
            }
        }

        return steps;
    }

    private static IReadOnlyList<DraftStep> CreateScreenDeltaSteps(JsonElement evt)
    {
        if (!evt.TryGetProperty("delta", out var delta) ||
            delta.ValueKind != JsonValueKind.Object ||
            !delta.TryGetProperty("added", out var added) ||
            added.ValueKind != JsonValueKind.Array)
        {
            return [];
        }

        var steps = new List<DraftStep>();
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var element in added.EnumerateArray())
        {
            var text = TryGetOptionalString(element, "text") ?? TryGetOptionalString(element, "content_description");
            if (string.IsNullOrWhiteSpace(text) || !seen.Add(text))
            {
                continue;
            }

            steps.Add(new DraftStep(
                new ScenarioStep("wait visible " + text, "waitVisible", text, null, null, TimeoutSec: 15),
                "screen_delta",
                "screen_delta",
                null,
                "added text: " + text,
                "medium"));
            if (steps.Count == 3)
            {
                break;
            }
        }

        return steps;
    }

    private static IReadOnlyList<DraftStep> CreateInspectCommandSteps(JsonElement evt)
    {
        if (!TryGetString(evt, "command", out var command) || TryGetBool(evt, "ok") is false)
        {
            return [];
        }

        var data = evt.TryGetProperty("data", out var dataElement) && dataElement.ValueKind == JsonValueKind.Object
            ? dataElement
            : default;
        if (command is "telemetry_tail" or "telemetry_watch")
        {
            return CreateTelemetrySteps(data);
        }

        var step = command switch
        {
            "tap_text" or "tap_element" or "tap_selector" => CreateSelectorOrTextStep(evt, data, "tapElement", "tapText", "tap element", "tap text"),
            "tap_point" => CreateTapPointStep(data),
            "wait_visible" or "wait_element" or "wait_selector" => CreateSelectorOrTextStep(evt, data, "waitElement", "waitVisible", "wait element", "wait visible"),
            "type_text" => CreateTextStep(evt, data, "typeText", "type text"),
            "keyevent" => TryGetString(data, "code", out var code)
                ? new ScenarioStep("keyevent " + code, "keyevent", null, code, null)
                : null,
            "screenshot" or "take_screenshot" => CreateLabelStep(data, "takeScreenshot", "screenshot"),
            _ => null
        };

        return step is null ? [] : [new DraftStep(step, "inspect_command", "command_result", command, CreateInspectCommandDetail(evt, command), "medium")];
    }

    private static ScenarioStep? CreateTapPointStep(JsonElement data)
    {
        if (!TryGetInt32(data, "x", out var x) || !TryGetInt32(data, "y", out var y))
        {
            return null;
        }

        var label = TryGetOptionalString(data, "label") ?? "replay-tap-point";
        return new ScenarioStep(
            "tap point " + label,
            "tapPoint",
            null,
            null,
            null,
            Label: label,
            X: x,
            Y: y,
            PostTapDelayMs: TryGetOptionalInt32(data, "post_tap_delay_ms") ?? TryGetOptionalInt32(data, "postTapDelayMs"));
    }

    private static IReadOnlyList<DraftStep> CreateTelemetrySteps(JsonElement data)
    {
        if (data.ValueKind != JsonValueKind.Object)
        {
            return [];
        }

        var steps = new List<DraftStep>();
        if (data.TryGetProperty("events", out var events) && events.ValueKind == JsonValueKind.Array)
        {
            steps.AddRange(events.EnumerateArray()
                .Select(CreateTelemetryStep)
                .OfType<ScenarioStep>()
                .Select(static step => new DraftStep(step, "telemetry", "command_result", "telemetry", step.Event ?? step.Step ?? step.Text, "medium")));
        }
        else
        {
            var step = CreateTelemetryStep(data);
            if (step is not null)
            {
                steps.Add(new DraftStep(step, "telemetry", "command_result", "telemetry", step.Event ?? step.Step ?? step.Text, "medium"));
            }
        }

        return steps;
    }

    private static ScenarioStep? CreateTelemetryStep(JsonElement telemetryEvent)
    {
        if (!TryGetString(telemetryEvent, "event", out var eventName))
        {
            return null;
        }

        if (string.Equals(eventName, "step", StringComparison.OrdinalIgnoreCase) &&
            TryGetString(telemetryEvent, "step", out var stepName))
        {
            return new ScenarioStep("wait step " + stepName, "waitStep", null, null, stepName, TimeoutSec: 15);
        }

        if (string.Equals(eventName, "action_ready", StringComparison.OrdinalIgnoreCase) &&
            TryGetString(telemetryEvent, "action", out var actionName))
        {
            TryGetString(telemetryEvent, "step", out var telemetryStepName);
            return new ScenarioStep("wait action " + actionName, "waitActionReady", actionName, null, string.IsNullOrWhiteSpace(telemetryStepName) ? null : telemetryStepName, TimeoutSec: 15);
        }

        return new ScenarioStep("assert event " + eventName, "assertEvent", null, null, null, Event: eventName, TimeoutSec: 15);
    }

    private static DraftStep? CreateScenarioStep(JsonElement evt, string eventType)
    {
        if (!TryGetString(evt, "action", out var action))
        {
            return null;
        }

        TryGetString(evt, "step", out var name);
        var stepName = name ?? action;
        return action switch
        {
            "waitVisible" or "waitNotVisible" or "tapText" or "typeText" or "waitLog" => TryGetString(evt, "text", out var text)
                ? new DraftStep(new ScenarioStep(stepName, action, text, null, null, TimeoutSec: action.StartsWith("wait", StringComparison.OrdinalIgnoreCase) ? 15 : null), "scenario_event", eventType, null, action + ": " + text, "high")
                : null,
            "waitElement" or "tapElement" => TryCreateSelector(evt, out var selector)
                ? new DraftStep(new ScenarioStep(stepName, action, null, null, null, TimeoutSec: action.StartsWith("wait", StringComparison.OrdinalIgnoreCase) ? 15 : null, Selector: selector), "scenario_event", eventType, null, action + ": " + selector.Describe(), "high")
                : null,
            "keyevent" => TryGetString(evt, "code", out var code)
                ? new DraftStep(new ScenarioStep(stepName, action, null, code, null), "scenario_event", eventType, null, "keyevent: " + code, "high")
                : null,
            "waitStep" => TryGetString(evt, "step", out var waitStep)
                ? new DraftStep(new ScenarioStep(stepName, action, null, null, waitStep, TimeoutSec: 15), "scenario_event", eventType, null, "waitStep: " + waitStep, "high")
                : null,
            "takeScreenshot" => new DraftStep(new ScenarioStep(stepName, action, null, null, null, Label: stepName), "scenario_event", eventType, null, action, "high"),
            "captureArtifacts" => new DraftStep(new ScenarioStep(stepName, action, null, null, null, Label: stepName), "scenario_event", eventType, null, action, "high"),
            _ => null
        };
    }

    private static DraftStep? CreateScreenshotStep(JsonElement evt, string eventType)
    {
        var label = TryGetOptionalString(evt, "label") ?? "replay-screenshot";
        return new DraftStep(new ScenarioStep("capture " + label, "takeScreenshot", null, null, null, Label: label), "view_event", eventType, null, "screenshot: " + label, "medium");
    }

    private static DraftStep? CreateKeyCommandStep(JsonElement evt, string eventType)
    {
        if (!TryGetString(evt, "command", out var command))
        {
            return null;
        }

        return new DraftStep(new ScenarioStep("key command " + command, "keyevent", null, command, null), "view_event", eventType, null, "key command: " + command, "medium");
    }

    private static ScenarioStep? CreateSelectorOrTextStep(JsonElement evt, JsonElement data, string selectorAction, string textAction, string selectorFallbackName, string textFallbackName)
    {
        if (TryCreateSelector(evt, out var selector))
        {
            var label = FirstNonBlank(selector.Text, selector.ContentDescription, LastResourceSegment(selector.ResourceId), selector.ClassName) ?? selector.Describe();
            return new ScenarioStep(
                selectorFallbackName + " " + label,
                selectorAction,
                null,
                null,
                null,
                TimeoutSec: selectorAction.StartsWith("wait", StringComparison.OrdinalIgnoreCase) ? 15 : null,
                Selector: selector);
        }

        return CreateTextStep(evt, data, textAction, textFallbackName);
    }

    private static ScenarioStep? CreateTextStep(JsonElement evt, JsonElement data, string action, string fallbackName)
    {
        if (!TryGetString(data, "text", out var text) &&
            !TryGetSelectorText(evt, out text))
        {
            return null;
        }

        return new ScenarioStep(fallbackName + " " + text, action, text, null, null, TimeoutSec: action.StartsWith("wait", StringComparison.OrdinalIgnoreCase) ? 15 : null);
    }

    private static ScenarioStep? CreateLabelStep(JsonElement data, string action, string fallbackLabel)
    {
        var label = TryGetOptionalString(data, "label") ?? fallbackLabel;
        return new ScenarioStep("capture " + label, action, null, null, null, Label: label);
    }

    private static IEnumerable<string> BuildWarnings(IReadOnlyList<ScenarioStep> steps)
    {
        if (steps.Any(static step => string.Equals(step.Action, "tapPoint", StringComparison.OrdinalIgnoreCase)))
        {
            yield return "Draft includes coordinate taps; add scenario metadata for device layout before using in CI.";
        }

        if (steps.All(static step =>
            !string.Equals(step.Action, "waitVisible", StringComparison.OrdinalIgnoreCase) &&
            !string.Equals(step.Action, "waitElement", StringComparison.OrdinalIgnoreCase)))
        {
            yield return "Draft has no waitVisible or waitElement steps; add waits around asynchronous UI transitions.";
        }
    }

    private static IEnumerable<ReplayScenarioDraftSuggestion> BuildSuggestions(IReadOnlyList<ScenarioStep> steps)
    {
        for (var i = 0; i < steps.Count; i++)
        {
            var step = steps[i];
            if (string.Equals(step.Action, "tapText", StringComparison.OrdinalIgnoreCase) &&
                !HasMatchingPreviousWait(steps, i))
            {
                yield return new ReplayScenarioDraftSuggestion(i + 1, "selector", "medium", "Review whether this tap should be preceded by waitVisible for the same text.");
            }
            else if (string.Equals(step.Action, "tapElement", StringComparison.OrdinalIgnoreCase) &&
                !HasMatchingPreviousWait(steps, i))
            {
                yield return new ReplayScenarioDraftSuggestion(i + 1, "selector", "medium", "Review whether this tap should be preceded by waitElement for the same selector.");
            }
            else if (string.Equals(step.Action, "tapPoint", StringComparison.OrdinalIgnoreCase))
            {
                yield return new ReplayScenarioDraftSuggestion(i + 1, "coordinate", "low", "Replace coordinate tap with tapText or add layout metadata if possible.");
            }
            else if (string.Equals(step.Action, "takeScreenshot", StringComparison.OrdinalIgnoreCase))
            {
                yield return new ReplayScenarioDraftSuggestion(i + 1, "visual", "medium", "Consider upgrading screenshot capture to assertScreenshot with a baseline or region hash.");
            }
            else if (string.Equals(step.Action, "waitStep", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(step.Action, "waitActionReady", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(step.Action, "assertEvent", StringComparison.OrdinalIgnoreCase))
            {
                yield return new ReplayScenarioDraftSuggestion(i + 1, "telemetry", "medium", "Verify this semantic telemetry assertion is emitted reliably by the app before using it as a CI gate.");
            }
        }
    }

    private static bool HasMatchingPreviousWait(IReadOnlyList<ScenarioStep> steps, int index)
    {
        if (index <= 0)
        {
            return false;
        }

        var wait = CreatePreTapWaitStep(steps[index]);
        return wait is not null &&
            string.Equals(GetWaitKey(steps[index - 1]), GetWaitKey(wait), StringComparison.OrdinalIgnoreCase);
    }

    private static IEnumerable<ReplayScenarioDraftReviewItem> BuildReviewItems(
        IReadOnlyList<string> warnings,
        IReadOnlyList<ReplayScenarioDraftSuggestion> suggestions,
        IReadOnlyList<ReplayScenarioDraftStepOrigin> origins,
        IReadOnlyList<ReplayScenarioDraftNormalization> normalizations)
    {
        foreach (var warning in warnings)
        {
            yield return new ReplayScenarioDraftReviewItem(
                "warning",
                "scenario",
                null,
                warning,
                "luotsi scenario-validate --file <scenario.json>");
        }

        foreach (var suggestion in suggestions)
        {
            var severity = string.Equals(suggestion.Confidence, "low", StringComparison.OrdinalIgnoreCase)
                ? "warning"
                : "info";
            yield return new ReplayScenarioDraftReviewItem(
                severity,
                suggestion.Kind,
                suggestion.StepIndex,
                suggestion.Message,
                BuildReviewCommand(suggestion.Kind));
        }

        foreach (var origin in origins.Where(static origin => string.Equals(origin.Confidence, "low", StringComparison.OrdinalIgnoreCase)))
        {
            yield return new ReplayScenarioDraftReviewItem(
                "warning",
                "provenance",
                origin.StepIndex,
                $"Low-confidence generated step from {origin.Source}; review against the source timeline before committing.",
                origin.SourceCommand ?? "luotsi replay timeline --artifacts <artifact-root> --context 3");
        }

        foreach (var origin in origins.Where(static origin => origin.Detail?.Contains("selector:", StringComparison.OrdinalIgnoreCase) is true))
        {
            yield return new ReplayScenarioDraftReviewItem(
                "info",
                "selector",
                origin.StepIndex,
                "Inspect selector metadata was captured in the replay origin. Generated scenario steps can now replay structured element selectors; verify resource_id/class/region constraints before committing.",
                origin.SourceCommand);
        }

        foreach (var normalization in normalizations)
        {
            yield return new ReplayScenarioDraftReviewItem(
                "info",
                "normalization",
                null,
                normalization.Detail,
                normalization.SourceCommand);
        }
    }

    private static string? BuildSourceCommand(string? sourcePath, int? sequence)
    {
        if (string.IsNullOrWhiteSpace(sourcePath) || sequence is null)
        {
            return null;
        }

        return $"luotsi replay timeline --artifacts <artifact-root> --source-path {Quote(sourcePath)} --sequence {sequence.Value} --context 2";
    }

    private static string Quote(string value) =>
        value.Contains(' ', StringComparison.Ordinal) ? "\"" + value.Replace("\"", "\\\"", StringComparison.Ordinal) + "\"" : value;

    private static string BuildValidateCommand(string output) =>
        $"luotsi scenario-validate --file {Quote(output)}";

    private static ReplayScenarioDraftRunHandoff? BuildRunHandoff(string? output, ReplayScenarioDraftValidation? validation, ScenarioFile scenario)
    {
        if (string.IsNullOrWhiteSpace(output))
        {
            return null;
        }

        if (validation is null)
        {
            return new ReplayScenarioDraftRunHandoff(
                "needs_validation",
                "Validate the generated scenario before planning or running it.");
        }

        if (!string.Equals(validation.Status, "validated", StringComparison.OrdinalIgnoreCase))
        {
            return new ReplayScenarioDraftRunHandoff(
                "blocked",
                "Resolve static validation errors before planning or running the generated scenario.");
        }

        var package = ResolvePreflightPackage(scenario);
        var serial = scenario.Metadata?.Device?.Serial;
        return new ReplayScenarioDraftRunHandoff(
            "ready",
            "Static validation passed; plan the generated scenario before running it on a selected device.",
            BuildPreflightCommand(package, serial),
            BuildDryRunCommand(output),
            BuildRunCommand(output, package, serial),
            BuildClaimedRunCommand(output, package, serial));
    }

    private static string? ResolvePreflightPackage(ScenarioFile scenario)
    {
        if (!string.IsNullOrWhiteSpace(scenario.Metadata?.Package))
        {
            return scenario.Metadata.Package;
        }

        return EnumerateScenarioSteps(scenario)
            .Where(step => !string.IsNullOrWhiteSpace(step.Package))
            .Select(step => step.Package)
            .FirstOrDefault();
    }

    private static IEnumerable<ScenarioStep> EnumerateScenarioSteps(ScenarioFile scenario)
    {
        foreach (var step in scenario.Setup ?? [])
        {
            yield return step;
        }

        foreach (var step in scenario.Steps)
        {
            yield return step;
        }

        foreach (var step in scenario.Teardown ?? [])
        {
            yield return step;
        }
    }

    private static string BuildPreflightCommand(string? package, string? serial)
    {
        var device = string.IsNullOrWhiteSpace(serial) ? "<serial>" : Quote(serial);
        return string.IsNullOrWhiteSpace(package)
            ? $"luotsi preflight --device {device} --package <app.id>"
            : $"luotsi preflight --device {device} --package {Quote(package)}";
    }

    private static string BuildDryRunCommand(string output) =>
        $"luotsi run --path {Quote(output)} --dry-run";

    private static string BuildRunCommand(string output, string? package, string? serial)
    {
        var device = string.IsNullOrWhiteSpace(serial) ? "<serial>" : Quote(serial);
        var command = $"luotsi run --file {Quote(output)} --device {device}";
        return string.IsNullOrWhiteSpace(package)
            ? command
            : command + $" --package {Quote(package)}";
    }

    private static string? BuildClaimedRunCommand(string output, string? package, string? serial)
    {
        if (string.IsNullOrWhiteSpace(package) || string.IsNullOrWhiteSpace(serial))
        {
            return null;
        }

        return $"luotsi run --file {Quote(output)} --device {Quote(serial)} --package {Quote(package)} --claim-device --claim-wait-sec 60";
    }

    private static string? BuildReviewCommand(string kind) =>
        kind switch
        {
            "selector" => "luotsi screen-state",
            "coordinate" => "luotsi scenario-validate --file <scenario.json>",
            "visual" => "luotsi replay open --artifacts <artifact-root>",
            "telemetry" => "luotsi telemetry-tail",
            _ => null
        };

    private static bool TryGetString(JsonElement root, string name, out string value)
    {
        value = string.Empty;
        if (root.ValueKind != JsonValueKind.Object ||
            !root.TryGetProperty(name, out var property) ||
            property.ValueKind != JsonValueKind.String ||
            string.IsNullOrWhiteSpace(property.GetString()))
        {
            return false;
        }

        value = property.GetString()!;
        return true;
    }

    private static string? TryGetOptionalString(JsonElement root, string name) =>
        TryGetString(root, name, out var value) ? value : null;

    private static bool TryGetSelectorText(JsonElement evt, out string text)
    {
        text = string.Empty;
        if (!TryCreateSelector(evt, out var selector) || string.IsNullOrWhiteSpace(selector.Text))
        {
            return false;
        }

        text = selector.Text;
        return true;
    }

    private static bool TryCreateSelector(JsonElement evt, out ScreenElementSelector selector)
    {
        selector = new ScreenElementSelector();
        if (evt.ValueKind != JsonValueKind.Object ||
            !evt.TryGetProperty("selector", out var source) ||
            source.ValueKind != JsonValueKind.Object)
        {
            return false;
        }

        var candidate = new ScreenElementSelector(
            TryGetOptionalString(source, "text"),
            TryGetOptionalString(source, "text_match", "textMatch") ?? ScreenElementMatchModes.Contains,
            TryGetOptionalString(source, "content_description", "contentDescription"),
            TryGetOptionalString(source, "content_description_match", "contentDescriptionMatch") ?? ScreenElementMatchModes.Exact,
            TryGetOptionalString(source, "resource_id", "resourceId"),
            TryGetOptionalString(source, "resource_id_match", "resourceIdMatch") ?? ScreenElementMatchModes.Exact,
            TryGetOptionalString(source, "class_name", "className"),
            TryGetOptionalString(source, "class_name_match", "classNameMatch") ?? ScreenElementMatchModes.Exact,
            TryGetSelectorRegion(source),
            TryGetBool(source, "allow_ambiguous", "allowAmbiguous") ?? false);

        if (!candidate.HasCriteria)
        {
            return false;
        }

        selector = ScreenElementSelectorValidator.Validate(candidate, "selector");
        return true;
    }

    private static Bounds? TryGetSelectorRegion(JsonElement selector)
    {
        if (!selector.TryGetProperty("region", out var region) ||
            region.ValueKind != JsonValueKind.Object ||
            !TryGetInt32(region, "left", out var left) ||
            !TryGetInt32(region, "top", out var top) ||
            !TryGetInt32(region, "right", out var right) ||
            !TryGetInt32(region, "bottom", out var bottom))
        {
            return null;
        }

        return new Bounds(left, top, right, bottom);
    }

    private static string? TryGetOptionalString(JsonElement root, params string[] names)
        => names
            .Select(name => TryGetString(root, name, out var value) ? value : null)
            .FirstOrDefault(static value => value is not null);

    private static bool? TryGetBool(JsonElement root, params string[] names)
        => names
            .Select(name => TryGetBool(root, name))
            .FirstOrDefault(static value => value is not null);

    private static string CreateInspectCommandDetail(JsonElement evt, string command) =>
        TryFormatSelector(evt, out var selector)
            ? $"{command} selector: {selector}"
            : command;

    private static bool TryFormatSelector(JsonElement evt, out string detail)
    {
        detail = string.Empty;
        if (evt.ValueKind != JsonValueKind.Object ||
            !evt.TryGetProperty("selector", out var selector) ||
            selector.ValueKind != JsonValueKind.Object)
        {
            return false;
        }

        var parts = new List<string>();
        AddSelectorPart(parts, selector, "text", "text_match", ScreenElementMatchModes.Contains);
        AddSelectorPart(parts, selector, "content_description", "content_description_match", ScreenElementMatchModes.Exact);
        AddSelectorPart(parts, selector, "resource_id", "resource_id_match", ScreenElementMatchModes.Exact);
        AddSelectorPart(parts, selector, "class_name", "class_name_match", ScreenElementMatchModes.Exact);
        if (selector.TryGetProperty("region", out var region) &&
            region.ValueKind == JsonValueKind.Object &&
            TryGetInt32(region, "left", out var left) &&
            TryGetInt32(region, "top", out var top) &&
            TryGetInt32(region, "right", out var right) &&
            TryGetInt32(region, "bottom", out var bottom))
        {
            parts.Add($"region={left},{top},{right},{bottom}");
        }

        if (TryGetBool(selector, "allow_ambiguous") is true)
        {
            parts.Add("allow_ambiguous=true");
        }

        detail = string.Join(", ", parts);
        return parts.Count > 0;
    }

    private static void AddSelectorPart(List<string> parts, JsonElement selector, string valueName, string matchName, string defaultMatch)
    {
        if (!TryGetString(selector, valueName, out var value))
        {
            return;
        }

        var match = TryGetOptionalString(selector, matchName) ?? defaultMatch;
        parts.Add($"{valueName}:{match}={value}");
    }

    private static string? LastResourceSegment(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        var index = value.LastIndexOf('/');
        return index >= 0 && index + 1 < value.Length ? value[(index + 1)..] : value;
    }

    private static string? FirstNonBlank(params string?[] values) =>
        values.FirstOrDefault(static value => !string.IsNullOrWhiteSpace(value));

    private static int? TryGetOptionalInt32(JsonElement root, string name) =>
        TryGetInt32(root, name, out var value) ? value : null;

    private static bool TryGetInt32(JsonElement root, string name, out int value)
    {
        value = 0;
        return root.ValueKind == JsonValueKind.Object &&
            root.TryGetProperty(name, out var property) &&
            property.ValueKind == JsonValueKind.Number &&
            property.TryGetInt32(out value);
    }

    private static bool? TryGetBool(JsonElement root, string name)
    {
        if (root.ValueKind != JsonValueKind.Object ||
            !root.TryGetProperty(name, out var property) ||
            property.ValueKind is not JsonValueKind.True and not JsonValueKind.False)
        {
            return null;
        }

        return property.GetBoolean();
    }

    private static DateTimeOffset? TryReadTimestamp(JsonElement root)
    {
        return new[] { "occurred_at", "occurredAt", "started_at", "startedAt", "ended_at", "endedAt" }
            .Select(name =>
                TryGetString(root, name, out var value) &&
                DateTimeOffset.TryParse(value, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.RoundtripKind, out var timestamp)
                    ? (DateTimeOffset?)timestamp
                    : null)
            .FirstOrDefault(timestamp => timestamp.HasValue);
    }

    private sealed record DraftTimelineEvent(
        string SourcePath,
        int Sequence,
        DateTimeOffset? Timestamp,
        JsonElement Element)
    {
        public DraftStep Attach(DraftStep step) =>
            step with
            {
                SourcePath = SourcePath,
                Sequence = Sequence,
                Timestamp = Timestamp
            };
    }

    private sealed record DraftStep(
        ScenarioStep Step,
        string Source,
        string EventType,
        string? Command,
        string? Detail,
        string Confidence,
        string? SourcePath = null,
        int? Sequence = null,
        DateTimeOffset? Timestamp = null);
}
