using System.Text;
using System.Text.Json;
using Luotsi.Cli.Cli;
using Luotsi.Cli.Errors;
using Luotsi.Cli.Infrastructure.Contracts;
using Luotsi.Cli.Infrastructure.Serialization;
using Luotsi.Cli.Models;

namespace Luotsi.Cli.Scenarios;

public sealed record ScenarioInitResult(
    string File,
    string Name,
    bool Overwrite,
    string Docs,
    IReadOnlyList<string> NextCommands);

public sealed record ScenarioExplainResult(
    string File,
    string Name,
    IReadOnlyList<string> Tags,
    int SetupStepCount,
    int StepCount,
    int TeardownStepCount,
    IReadOnlyList<string> Actions,
    ScenarioMetadata? Metadata,
    IReadOnlyList<string> Docs,
    IReadOnlyList<string> SuggestedCommands);

internal sealed class ScenarioAuthoringService(IFileSystem fileSystem, ScenarioCatalog scenarioCatalog)
{
    private const string DefaultDocsUrl = "docs/tutorials/buggy-controller-live-demo.md";
    private readonly IFileSystem _fileSystem = fileSystem ?? throw new ArgumentNullException(nameof(fileSystem));
    private readonly ScenarioCatalog _scenarioCatalog = scenarioCatalog ?? throw new ArgumentNullException(nameof(scenarioCatalog));

    public async Task<ScenarioInitResult> InitAsync(CliOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);

        var file = options.Get("file") ?? options.Get("output") ?? "scenarios/smoke.json";
        var name = options.Get("name") ?? Path.GetFileNameWithoutExtension(file).Replace('-', ' ').Replace('_', ' ');
        var package = options.Get("package") ?? "com.example.app";
        var activity = options.Get("activity") ?? ".MainActivity";
        var overwrite = options.HasFlag("force") || options.HasFlag("overwrite");
        if (_fileSystem.FileExists(file) && !overwrite)
        {
            throw new UsageException($"Scenario file '{file}' already exists. Use --force to overwrite it.");
        }

        var scenario = new ScenarioFile(
            name,
            [
                new ScenarioStep("wait for home", "waitVisible", "Home", null, null, TimeoutSec: 15),
                new ScenarioStep("capture screenshot", "takeScreenshot", null, null, null, Label: "home")
            ],
            Variables: new Dictionary<string, string>
            {
                ["targetPackage"] = package,
                ["targetActivity"] = activity
            },
            Tags: ["smoke", "generated"],
            Setup:
            [
                new ScenarioStep("start app", "startApp", null, null, null, Package: "${var:targetPackage}", Activity: "${var:targetActivity}", Wait: true)
            ],
            Teardown:
            [
                new ScenarioStep("collect artifacts", "captureArtifacts", null, null, null, Label: "teardown")
            ],
            Metadata: new ScenarioMetadata(
                package,
                activity,
                $"Generated by `luotsi scenario-init`. See {DefaultDocsUrl} for a complete tutorial.",
                new ScenarioDeviceMetadata(Model: options.Get("model"), AndroidRelease: options.Get("android-release"), Sdk: options.Get("sdk")),
                new ScenarioLayoutMetadata(
                    TryParseOptionalInt(options.Get("width")),
                    TryParseOptionalInt(options.Get("height")),
                    options.Get("orientation"))));

        var text = JsonSerializer.Serialize(scenario, AppJson.Options) + Environment.NewLine;
        var directory = Path.GetDirectoryName(file);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            _fileSystem.CreateDirectory(directory);
        }

        await _fileSystem.WriteAllTextAsync(file, text, new UTF8Encoding(false)).ConfigureAwait(false);

        return new ScenarioInitResult(
            file,
            name,
            overwrite,
            DefaultDocsUrl,
            [
                $"luotsi scenario-validate --file {file}",
                $"luotsi run --file {file} --validate-only",
                $"luotsi run --file {file} --device <adb serial> --report-junit junit.xml"
            ]);
    }

    public async Task<ScenarioExplainResult> ExplainAsync(CliOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);

        var file = options.Require("file");
        var scenario = await _scenarioCatalog.LoadValidatedAsync(file, ScenarioExecutor.SupportedScenarioActions).ConfigureAwait(false);
        var actions = ScenarioCatalog.EnumerateLifecycleSteps(scenario)
            .Select(static step => step.Action)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(static action => action, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        return new ScenarioExplainResult(
            file,
            scenario.Name,
            scenario.Tags ?? [],
            scenario.Setup?.Count ?? 0,
            scenario.Steps.Count,
            scenario.Teardown?.Count ?? 0,
            actions,
            scenario.Metadata,
            [DefaultDocsUrl],
            [
                $"luotsi scenario-list --path {file}",
                $"luotsi scenario-validate --file {file}",
                $"luotsi run --file {file} --device <adb serial>"
            ]);
    }

    private static int? TryParseOptionalInt(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        return int.TryParse(value, out var parsed) ? parsed : throw new UsageException($"Expected integer metadata value, got '{value}'.");
    }
}
