<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>luotsi</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RuntimeIdentifiers>win-x64;linux-x64;osx-arm64;osx-x64</RuntimeIdentifiers>
    <RuntimeIdentifier Condition="'$(PublishRid)' != ''">$(PublishRid)</RuntimeIdentifier>
    <PublishSingleFile Condition="'$(PublishSingleFile)' == ''">true</PublishSingleFile>
    <SelfContained Condition="'$(SelfContained)' == ''">true</SelfContained>
    <PublishTrimmed Condition="'$(PublishTrimmed)' == ''">false</PublishTrimmed>
    <IncludeNativeLibrariesForSelfExtract Condition="'$(IncludeNativeLibrariesForSelfExtract)' == ''">true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen" Version="8.1.0" />
    <PackageReference Include="ppy.SDL3-CS" Version="2025.1115.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\luotsi-icon.bmp" LogicalName="Luotsi.Cli.Assets.luotsi-icon.bmp" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\ffmpeg\download-ffmpeg.ps1"
             Link="ffmpeg\download-ffmpeg.ps1"
             CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\Luotsi.ViewServer.Android\**\*"
             Exclude="..\Luotsi.ViewServer.Android\**\bin\**;..\Luotsi.ViewServer.Android\**\obj\**;..\Luotsi.ViewServer.Android\**\.gradle\**;..\Luotsi.ViewServer.Android\**\build\**"
             Link="Luotsi.ViewServer.Android\%(RecursiveDir)%(Filename)%(Extension)"
             CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\Luotsi.ViewServer.Android\app\build\outputs\apk\debug\app-debug.apk"
             Link="Luotsi.ViewServer.Android\app\build\outputs\apk\debug\app-debug.apk"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
